### ISSUE TITLE
DotPlot color of the dot always grey

### ISSUE THREAD

**Issue by JihedC** [satijalab/seurat#2342]
Hello,
I am using Seurat since few weeks now and I found it great! I would like to compare the gene expression of clusters I have identified after integration of data from a control and a treated samples.
Dotplot would be great to have a normalized gene expression per cluster but I can't make It work as in the example [here](https://satijalab.org/seurat/v3.1/immune_alignment.html)

This is the code :
```
DotPlot(sample, features = c("Tcf7", "Cd3e"), cols = c("blue", "red"), dot.scale = 8, split.by = "orig.ident") + RotatedAxis()
```

and this is the output
<img width="582" alt="Capture d’écran 2019-11-20 à 14 53 32" src="https://user-images.githubusercontent.com/22910541/69244620-8eb5a600-0ba5-11ea-9639-1405224ed28c.png">

I would like to have a different color for the control and the stimulated but I can't get it to work.
Can someone help me?

Jihed

**Comment by samuel-marsh** [comment]
Hi Jihed,

Not a member of the Dev team but hopefully this helps.  So your example code isn't attempting to do the same thing as the DotPlot in the Vignette you linked which is likely the issue.

In the Vignette:
`DotPlot(immune.combined, features = rev(markers.to.plot), cols = c("blue", "red"), dot.scale = 8, 
    split.by = "stim") + RotatedAxis()`
Specifically, the key is the `split.by` argument.  In the Vignette they splitting by the condition from metadata "stim".

You are splitting by "orig.ident" which isn't doing the same thing.  If you change `split.by` to be whatever you have named that information in your metadata slot does that solve the issue?

Best,
Sam

**Comment by JihedC** [comment]
Hi @samuel-marsh ,

Thanks for your quick reply! 
I have tried to change the `split.by` argument by `sample` which is a metadata column indicating whether the cell is coming from an heterozygous or an homozygous sample. And it still doesn't work. :( 

```
DotPlot(test, features = c("Tcf7", "Cd3e"), cols = c("blue", "red"), dot.scale = 8, split.by = "sample") + RotatedAxis()
```
<img width="965" alt="Capture d’écran 2019-11-21 à 11 15 32" src="https://user-images.githubusercontent.com/22910541/69328857-4acbab00-0c50-11ea-82ee-8f4bd88e14cd.png">

I tried the to split for the violin plot and it works nicely also with `split.by = "origine.ident"`. I don't know why it's not working.
Best,
Jihed

**Comment by trueth1206** [comment]
Hi, you can try to use "-" instead of "_" in your cluster name. A cluster name with any "_" will result in grey dots (seems a bug...).

**Comment by satijalab** [comment]
Thanks for pointing this out , we will fix (@timoast)

**Comment by giovanegt** [comment]
I am facing the same problem described above. Did anybody come up with a way to fix it? @satijalab

**Comment by mojaveazure** [comment]
This should be fixed in the development version of Seurat. To install the development version of Seurat, please see the instructions [here](https://satijalab.org/seurat/install.html#development).

**Comment by JihedC** [comment]
Thanks!

**Comment by InternetExplorerBoy** [comment]
Dear @timoast, dear @mojaveazure,

I'm posting my issue to this one, since I feel it's closely related to this previous bug.

I am on Seurat Version 4.0.3 and when I plot gene expression using `DotPlot()` and split by two different experimental conditions, I get grey dots for some of the clusters. Upon closer inspection, I believe that a `"+"` symbol in cluster names might be the cause of this, similarly as the `"_"` symbol caused this issue for OP.

![DotPlot_Test](https://user-images.githubusercontent.com/60901344/131225684-d565e629-4bdc-4e5c-829a-8b42e4cd61b2.png)

Thank you and keep up the great work!

**Comment by kaushalmb** [comment]
I am still facing this issue. I tried replacing "_" with "-" in the labels on the y axis and it didn't work. What is the solution to this very annoying issue? :(

**Comment by kasumaz** [comment]
Dear all, 
I am too facing the same issues.  

I am using Seurat ver ‘4.0.4’.  

Here is the code I am using: 

DotPlot(object = comb6, features = c("Tcf7l2", "Lef1", "Pygo2", "Tle1", "Ctnnb1", "Axin2", "Gsk3b"), group.by = "mycells", split.by = "ages", cols = c("red", "blue", "green", "orange", "purple"))  

Has anyone worked out a solution to the problem?   I would love to know. Been at it since a day now :P 
Thanks a lot.

**Comment by kaushalmb** [comment]
> 
> 
> Dear all,
> I am too facing the same issues.
> 
> I am using Seurat ver ‘4.0.4’.
> 
> Here is the code I am using:
> 
> DotPlot(object = comb6, features = c("Tcf7l2", "Lef1", "Pygo2", "Tle1", "Ctnnb1", "Axin2", "Gsk3b"), group.by = "mycells", split.by = "ages", cols = c("red", "blue", "green", "orange", "purple"))
> 
> Has anyone worked out a solution to the problem? I would love to know. Been at it since a day now :P
> Thanks a lot.

I could not solve the bug but I just went ahead with an alternate visualization of plotting the data in facets instead of the split.by option. The grouped data was plotted in facets. Let me know if you need the code for it.

**Comment by kasumaz** [comment]
> > Dear all,
> > I am too facing the same issues.
> > I am using Seurat ver ‘4.0.4’.
> > Here is the code I am using:
> > DotPlot(object = comb6, features = c("Tcf7l2", "Lef1", "Pygo2", "Tle1", "Ctnnb1", "Axin2", "Gsk3b"), group.by = "mycells", split.by = "ages", cols = c("red", "blue", "green", "orange", "purple"))
> > Has anyone worked out a solution to the problem? I would love to know. Been at it since a day now :P
> > Thanks a lot.
> 
> I could not solve the bug but I just went ahead with an alternate visualization of plotting the data in facets instead of the split.by option. The grouped data was plotted in facets. Let me know if you need the code for it.

Yes please. This would be so very helpful for anyone else facing the same issues. :) 
I can inform on how I get a long so that others can see a solution. 
Thanks a lot.

**Comment by kaushalmb** [comment]
> 
> 
> > > Dear all,
> > > I am too facing the same issues.
> > > I am using Seurat ver ‘4.0.4’.
> > > Here is the code I am using:
> > > DotPlot(object = comb6, features = c("Tcf7l2", "Lef1", "Pygo2", "Tle1", "Ctnnb1", "Axin2", "Gsk3b"), group.by = "mycells", split.by = "ages", cols = c("red", "blue", "green", "orange", "purple"))
> > > Has anyone worked out a solution to the problem? I would love to know. Been at it since a day now :P
> > > Thanks a lot.
> > 
> > 
> > I could not solve the bug but I just went ahead with an alternate visualization of plotting the data in facets instead of the split.by option. The grouped data was plotted in facets. Let me know if you need the code for it.
> 
> Yes please. This would be so very helpful for anyone else facing the same issues. :)
> I can inform on how I get along so that others can see a solution.
> Thanks a lot.

This is the code for the plot that provides an alternate visualization -
replace <- Vectorize(function(x) {
  gsub("_"," ",x)
  })
DotPlot(Seuratobject, features = c(< gene names you want to include>), group.by=  "subclass", dot.scale = 30) + RotatedAxis() + labs(y="Class", x = "Genes") + theme(axis.text=element_text(size=13)) + scale_y_discrete(labels = replace) +theme(panel.grid.minor = element_blank(),panel.grid.major = element_line(colour = "gray",linetype = "dashed", size=0.35), panel.border = element_rect(colour = "black", fill=NA, size=2))+ facet_grid(~ unique(Seuratobject@meta.data$condition))


![seurat_reply_github](https://user-images.githubusercontent.com/45987758/134114719-8fb3f6cc-b6b3-45ac-9a39-e1f9193691cd.png)

**Comment by kaushalmb** [comment]
> 
> 
> Hi, you can try to use "-" instead of "_ " in your cluster name. A cluster name with any "_" will result in grey dots (seems a bug...).

Could you kindly help me understand how to do that? I tried changing the label names and it did not help.

**Comment by Kadd-L** [comment]
Hi, I had the same problem earlier, and my code below worked well. So if you split your dataset, you need a multidimensional vector of the color panel. 

# Set a color panel, row number should be equal to how many splits(conditions) you have. 
x1 <- c("Pink", "Blue")
x2 <- c("Pink", "Red")
panel <- data.frame(x1, x2)

# Make a feature index without duplicate
top10 = top10[!duplicated(top10$gene),]
select_genes_all = split(top10$gene,top10$cluster)
select_genes_all

# Dotplot
dotcluster <- DotPlot(object = merge.sp, 
                      features=select_genes_all, 
                      split.by = 'stim',
                      cols = panel)  + theme(axis.text.x = element_text(angle = 90, 
                                                                         vjust = 0.5, hjust=0.5, size = 10.5))

Here is my sample figure. I hope it helps. 

<img width="1428" alt="Screen Shot 2022-10-18 at 14 01 25" src="https://user-images.githubusercontent.com/10805429/196509008-0b5080fb-adaa-4ba6-8b68-e9d132ac4547.png">
