### ISSUE TITLE
FindVariableFeatures: Error in simpleLoess(y, x, w, span, degree = degree, parametric = parametric,  :    invalid 'x'

### ISSUE THREAD

**Issue by grimwoo** [satijalab/seurat#2387]
In brief, when I ran 
```
FindIntegrationAnchors
```
, I got the error :
```
>   Patient.anchors <- FindIntegrationAnchors(object.list = list(Patient.object, Other.Objct), scale = FALSE, anchor.features = 3000, dims = 1:50)
Computing 3000 integration features
No variable features found for object1 in the object.list. Running FindVariableFeatures ...
Calculating gene variances
0%   10   20   30   40   50   60   70   80   90   100%
[----|----|----|----|----|----|----|----|----|----|
**************************************************|
Error in simpleLoess(y, x, w, span, degree = degree, parametric = parametric,  : 
  invalid 'x'
```

Hence, I tried ```FindVariableFeatures```, but I got :
```
>   Patient.object <- FindVariableFeatures(Patient.object, selection.method = "vst", nfeatures = 2000)
Calculating gene variances
0%   10   20   30   40   50   60   70   80   90   100%
[----|----|----|----|----|----|----|----|----|----|
**************************************************|
Error in simpleLoess(y, x, w, span, degree = degree, parametric = parametric,  : 
  invalid 'x'
```

In details, I had an integrated seurat object. For further analysis, I  subset some clusters together and resulted in another 3 subset objects. latter, I figured out the real cluster names for them and merged the 3 subset objects back to one seurat object (Patient.object). For correlation, I use another seurat object (Other.Objct) to analyze the correlation among clusters of this two seurat objects. Unfortunately, I encountered the error in the very first step  (
```
FindIntegrationAnchors
```
). Could you let me know why I have such an error? Or how to solve it?

Information of this two seurat objects:
```
> Patient.object
An object of class Seurat 
26355 features across 25060 samples within 2 assays 
Active assay: integrated (3000 features)
 1 other assay present: RNA
> Other.Objct
An object of class Seurat 
30879 features across 43261 samples within 2 assays 
Active assay: RNA (28879 features)
 1 other assay present: integrated
 3 dimensional reductions calculated: pca, umap, tsne
```

**Comment by grimwoo** [comment]
I later used the following code, but still can not integrate those data. the problem may be due to the fact that one is human and another object is rodent. 
I just paste the code below if anyone may needed it:
```
  Other.Objct <- FindVariableFeatures(Other.Objct, assay = "RNA")
  Patient.object <- FindVariableFeatures(Patient.object, assay = "RNA")
  Patient.object <- ScaleData(Patient.object, verbose = TRUE, assay = "RNA")
  Patient.object <- RunPCA(Patient.object, npcs = 30, verbose = TRUE, resolution = 0.1, assay = "RNA")
  Patient.anchors <- FindIntegrationAnchors(object.list = list(Patient.object, Other.Objct), scale = TRUE, anchor.features = 3000, dims = 1:50, assay = c("RNA", "RNA"))
#the next step still resulted in error.  
Patient.object <- IntegrateData(anchorset = Patient.anchors)
```

**Comment by suvi93** [comment]
I'm getting the same error with FindVariableFeatures(), is there any solution to this?

**Comment by maximilianh** [comment]
I'm getting the same error with FindVariableFeatures(), on the old quake lab brain dataset (467 cells)

**Comment by shefalipatel7** [comment]
I'm also getting the same error with FindVariableFeatures(). I subsetted based on cell type identities and then merged two of subsetted objects into one. I then tried using FindVariableFeatures() and got this same error. Is there something in the object formation that may be causing this?

**Comment by Danvor** [comment]
I am trying to combine two very similar datasets (some cells in the two objects are the same but have different barcode identifiers stating original identity) and get the same error.

**Comment by satijalab** [comment]
This error can occur if you forget to run NormalizeData prior to finding variable features (I make this mistake all the time). The problem is that some of the values get astronomically large after exponentiation, which causes errors.

Closing this now as that should fix the problem, but if it does not, please reopen

**Comment by aheravi** [comment]
I am still getting the error after running the normalization step:

>   pbmc <- NormalizeData(pbmc)
Performing log-normalization
0%   10   20   30   40   50   60   70   80   90   100%
[----|----|----|----|----|----|----|----|----|----|
**************************************************|


>   pbmc <- FindVariableFeatures(pbmc, selection.method = "vst", nfeatures = 2000)
Calculating gene variances
0%   10   20   30   40   50   60   70   80   90   100%
[----|----|----|----|----|----|----|----|----|----|
**************************************************|
Error in simpleLoess(y, x, w, span, degree = degree, parametric = parametric,  : 
  invalid 'x'

**Comment by suvi93** [comment]
Please check your input matrix. There may be a column with text somewhere in the middle with all your read counts and that's causing this error. That's what had happened to me and I rectified it by making my matrix again.

**Comment by aheravi** [comment]
Thanks, @suvi93 . Limiting the expression matrix to the protein-coding ones resolved the issue. 
Could you also please comment on the error I am getting here:

>   pbmc <- RunPCA(pbmc, features = VariableFeatures(object = pbmc))
Error in irlba(A = t(x = object), nv = npcs, ...) : 
  max(nu, nv) must be strictly less than min(nrow(A), ncol(A))

>   pbmc <- RunPCA(pbmc)
Error in irlba(A = t(x = object), nv = npcs, ...) : 
  max(nu, nv) must be strictly less than min(nrow(A), ncol(A))

> nrow(pbmc)
[1] 6716
> ncol(pbmc)
[1] 4

>   pbmc <- RunPCA(pbmc, nfeatures.print = 4)
Error in irlba(A = t(x = object), nv = npcs, ...) : 
  max(nu, nv) must be strictly less than min(nrow(A), ncol(A))

**Comment by suvi93** [comment]
please refer to #1938

**Comment by Yale73** [comment]
@suvi93 Hi, I also ran the same issue and can not fix it after running the normalization. I am wondering how you know there is a column with text and how you rectify it. Is it OK for you to share the code?

Thanks,
Yale

**Comment by suvi93** [comment]
@Yale73 Please check your input file again, there could be a mistake when you made it. Remaking the input file solved my issue.

**Comment by Yale73** [comment]
@suvi93 I finally fixed it by **CreateAssayObject()** using the same data matrix. The following is my code. 
Old is the object that doesn't work, while New is the assay object created based on the old object data.

```
New <- CreateAssayObject(counts = Old@assays[["RNA"]]@data)
New <- NormalizeData(New, verbose = T, normalization.method = "LogNormalize") %>% FindVariableFeatures(selection.method = "vst", nfeatures = 2000) %>% ScaleData()

###add counts and the scale data to the Old object
Old@assays[["RNA"]]@counts <- New@counts
Old@assays[["RNA"]]@scale.data <- New@scale.data

Old <- NormalizeData(New, verbose = T, normalization.method = "LogNormalize") %>% FindVariableFeatures(selection.method = "vst", nfeatures = 2000) %>% ScaleData() %>% RunPCA()

```
Thanks for any correction.
Yale

**Comment by rmicheroli** [comment]
Just as a general comment (which was not mentioned before).
Before you merge the two Seurat objects you have to set DefaultAssay to "RNA" (DefaultAssay(object = Seuratobj) <- "RNA")

**Comment by Blowfish82** [comment]
Hi everyone, I ran into the same issue.
I think the problem is, that in some objects the DefaultAssay is set to "integrated" and not "RNA"
Check this with: `DefaultAssay(object = seurat.object)`
Resetting the default to "RNA" with `DefaultAssay(object = seurat.object) <- "RNA" `should solve the problem. Do this before you merge the objects or before creating a list of objects. After that, I had no problems with `SelectIntegrationFeatures`. 
You don´t have to Create all Objects from the scratch like proposed.

Hope this helps!

**Comment by Junedays** [comment]
I have similar problems when I download the count csv data from geo.  But I figured it out that it is because the count csv data contains NA data and if we use fread to import it, the dataframe would contains lots of NA, rather than 0. During the creatseuratobject process, all of the NA would be preserved when the dataframe was converted to dgCmatrix. This would cause the error. The solution is to convert the NA of the imported count csv to 0 before putting it into createseuratobject.

**Comment by yogesh601** [comment]
Simply please set your default assay to RNA

DefaultAssay(seurat.object)<- "RNA"

hope this will work.
good luck

**Comment by Ibisanmi1** [comment]
pbmc.rna <- FindVariableFeatures(pbmc.rna, selection.method = "vst", nfeatures = 2000)
Calculating gene variances
0%   10   20   30   40   50   60   70   80   90   100%
[----|----|----|----|----|----|----|----|----|----|
**************************************************|
Calculating feature variances of standardized and clipped values
0%   10   20   30   40   50   60   70   80   90   100%
[----|----|----|----|----|----|----|----|----|----|
**************************************************|
Error in match.arg(arg = layer, choices = Layers(object = object, search = FALSE)) : 
  'arg' should be one of "counts", "data", "scale.data"

**Comment by levinhein** [comment]
Hi @Ibisanmi1 I am experiencing same problem as yours. May I know if you've resolved that error in match.arg after running FindVariableFeatures()?

**Comment by yogesh601** [comment]
Hi Did you try setting your object as 
DefaultAssay(Seurat.object)<- "RNA"
It should work

**Comment by levinhein** [comment]
Hi @yogesh601 Yes, I did make sure to set that for all the datasets as you previously indicated, but still to no avail.

**Comment by yogesh601** [comment]
DefaultAssay(seurat.object)<-"integrated"     ##   or as  "RNA"
seurat.object <- FindVariableFeatures(object = seurat.object)
seurat.object <- ScaleData(seurat.object, verbose = FALSE)
seurat.object <- RunPCA(seurat.object, npcs = 30, verbose = FALSE)
seurat.object <- RunUMAP(seurat.object, reduction = "pca", dims = 1:20)
seurat.object <- FindNeighbors(seurat.object, reduction = "pca", dims = 1:20)
seurat.object <- FindClusters(seurat.object, resolution = 1)
DimPlot(seurat.object, label = TRUE)


@levinhein Could you try running all these line in same sequence
Then let me know it you get error.

**Comment by Ibisanmi1** [comment]
> Hi @Ibisanmi1 I am experiencing same problem as yours. May I know if you've resolved that error in match.arg after running FindVariableFeatures()?

Good day, you can try to remove and delete the object from the environment, then load it back. let me know if that works.
Good Luck!

**Comment by Jasemineonly** [comment]
> In brief, when I ran
> 
> ```
> FindIntegrationAnchors
> ```
> 
> , I got the error :
> 
> ```
> >   Patient.anchors <- FindIntegrationAnchors(object.list = list(Patient.object, Other.Objct), scale = FALSE, anchor.features = 3000, dims = 1:50)
> Computing 3000 integration features
> No variable features found for object1 in the object.list. Running FindVariableFeatures ...
> Calculating gene variances
> 0%   10   20   30   40   50   60   70   80   90   100%
> [----|----|----|----|----|----|----|----|----|----|
> **************************************************|
> Error in simpleLoess(y, x, w, span, degree = degree, parametric = parametric,  : 
>   invalid 'x'
> ```
> 
> Hence, I tried `FindVariableFeatures`, but I got :
> 
> ```
> >   Patient.object <- FindVariableFeatures(Patient.object, selection.method = "vst", nfeatures = 2000)
> Calculating gene variances
> 0%   10   20   30   40   50   60   70   80   90   100%
> [----|----|----|----|----|----|----|----|----|----|
> **************************************************|
> Error in simpleLoess(y, x, w, span, degree = degree, parametric = parametric,  : 
>   invalid 'x'
> ```
> 
> In details, I had an integrated seurat object. For further analysis, I subset some clusters together and resulted in another 3 subset objects. latter, I figured out the real cluster names for them and merged the 3 subset objects back to one seurat object (Patient.object). For correlation, I use another seurat object (Other.Objct) to analyze the correlation among clusters of this two seurat objects. Unfortunately, I encountered the error in the very first step (
> 
> ```
> FindIntegrationAnchors
> ```
> 
> ). Could you let me know why I have such an error? Or how to solve it?
> 
> Information of this two seurat objects:
> 
> ```
> > Patient.object
> An object of class Seurat 
> 26355 features across 25060 samples within 2 assays 
> Active assay: integrated (3000 features)
>  1 other assay present: RNA
> > Other.Objct
> An object of class Seurat 
> 30879 features across 43261 samples within 2 assays 
> Active assay: RNA (28879 features)
>  1 other assay present: integrated
>  3 dimensional reductions calculated: pca, umap, tsne
> ```

Dear grimwoo,
  Could you tell how to fix this problem？I have two seurat objects, one of which is pre integrated. Now I want to combine the two for analysis. What should I do? I feel like setting the integrated matrix for analysis, but the above error will occur again. How did you solve it? Could you tell me your code?
Thank you very much.

**Comment by Blowfish82** [comment]
Dear Jasmineonly,

I would suggest to set every seurat object assay to "RNA" . 
```
DefaultAssay(Patient.object )<- "RNA"
DefaultAssay(Other.Objct )<- "RNA"
```

and then start with `Patient.anchors <- FindIntegrationAnchors.(....` again

**Comment by Jasemineonly** [comment]
> Dear Jasmineonly,
> 
> I would suggest to set every seurat object assay to "RNA" .
> 
> ```
> DefaultAssay(Patient.object )<- "RNA"
> DefaultAssay(Other.Objct )<- "RNA"
> ```
> 
> and then start with `Patient.anchors <- FindIntegrationAnchors.(....` again

Hi Blowfish82,thank you for your answer,I have some confuses.My first seurat object because of patient differences so it need to be integrated,and after integrated the first seurat object will have two assay:RNA;integrated.My second seurat object only has one assay:RNA.I want to use the integrated assay of the first seurat object to merge and do the downstream analysis with the RNA assay of the second seurat object,if we choose the both RNA assay,how could we achieve our goal? Isn't the first integrated assay useless？

**Comment by Blowfish82** [comment]
Dear Jasmineonly,

in my opinion integration is the way to make unequal datasets comparable. To quote: "can be used both to correct for technical differences between datasets (i.e. batch effect correction), and to perform comparative scRNA-seq analysis of across experimental conditions" from https://satijalab.org/seurat/articles/integration_introduction.html

If you follow loosely this turorial (including `FindIntegrationAnchors`), it should be possible to integrate those different datasets even when you set their assay to "RNA".
How did you integrate your first dataset?

**Comment by Jasemineonly** [comment]
Hi Blowfish82，I used the offcial turorial from https://satijalab.org/seurat/articles/integration_introduction.html to integrate the first object ,because the same cluster between different patients could not gather tother well

**Comment by sweet0cat** [comment]
good day. After running this line of code, the problem was easily solved：
object <- JoinLayers(object)#object is your object
