### ISSUE TITLE
error with FindTransferAnchors (rowNamesDF)

### ISSUE THREAD

**Issue by wangmhan** [satijalab/seurat#2981]
Hi,
 
I come up with error during integrate scATAC and scRNA data.
Error in `.rowNamesDF<-`(x, value = value) : invalid 'row.names' length

I check the name of my gene activity assay, they are named properly:
3 x 3 sparse Matrix of class "dgCMatrix"
GetAssayData(mtx.fl)[1:3,1:3]
                   AAACGAAAGTCAGGAC-1 AAACGAAAGTTCGTTG-1 AAACGAAGTCAGGTGA-1
ENSGALG00000029624          .                    .                  .      
ENSGALG00000038527          0.6302238            0.57799            .      
ENSGALG00000050315          1.0138027            .                  1.26676

GetAssayData(mtx.fl_rna)[1:3,1:3]
3 x 3 sparse Matrix of class "dgCMatrix"
                   N18_AAACCTGAGCGACGTA.1 N18_AAACCTGAGCTGAAAT.1 N18_AAACCTGCACGGCCAT.1
ENSGALG00000035824            -0.19496051            -0.05178158            -0.14029140
ENSGALG00000032868            -0.08578131            -0.07247067            -0.05073724
ENSGALG00000006409            -0.36117167            -0.40427536            -0.33158749

But still, I got the error: Error in `.rowNamesDF<-`(x, value = value) : invalid 'row.names' length.
I just update my seurat to the developing version, still has the same problem:
packageVersion("Seurat")
[1] '3.1.5.9003'

Thanks & best,
Menghan

**Comment by gbloeb** [comment]
Having the same issue

**Comment by satijalab** [comment]
Thanks - would it be possible to send the exact commands you're using to run integration? Please check

1. Assays are set correctly
2. Features you are setting to integrate are present in both objects

**Comment by wangmhan** [comment]
Hi, thanks for the reply.
I fixed it latter by reconstructing the whole signac file.
The thing is I first integrated the scATAC with another scRNA file, then
tried to integrate with this scRNA file, turned out to error. So my guess
is that might be conflict when the transfer data already existed.
So I rerun everything, then integrate only with this scRNA and it worked
finally.

**Comment by aleksandrPi** [comment]
I am having the same error, when trying to do FindTransferAnchors on my scATAC with a published .rds from NCBI. Interestingly, if I do the same with my own scRNA data, there is no such problem. The problem persists both with the current and devel versions of Seurat, and only finally worked after down-grading to Seurat 3.1.1, however, this version is said to be incompatible with Signac v1.0, so not a solution for the time being... Any recommendations?
