### ISSUE TITLE
Installing development version of Seurat failed

### ISSUE THREAD

**Issue by elegans1121** [satijalab/seurat#3002]
I need to install Seurat through github to resolve issue with publishing apps to shinyapps.io (#2716 ), but I have a similar problem with #2945 for installing through github.

I ran `devtools::install_github(repo = 'satijalab/seurat', ref = 'develop')` as instrcutred, and the installation failed with this error message.

installing to /Library/Frameworks/R.framework/Versions/4.0/Resources/library/00LOCK-Seurat/00new/Seurat/libs
** R
** data
*** moving datasets to lazyload DB
/Library/Frameworks/R.framework/Resources/bin/INSTALL: line 34: 69313 Done                    echo 'tools:::.install_packages()'
     69314 Killed: 9               | R_DEFAULT_PACKAGES= LC_COLLATE=C "${R_HOME}/bin/R" $myArgs --no-echo --args ${args}
Error: Failed to install 'Seurat' from GitHub:
  (converted from warning) installation of package ‘/var/folders/g4/m3gngl812p72ck28fxxxrgcr0000gn/T//RtmpgdfQjI/file1061515d6a4eb/Seurat_3.1.5.9003.tar.gz’ had non-zero exit status

I tried to install through `devtools::install_github(repo = 'satijalab/seurat')` but got a similar message.

installing to /Library/Frameworks/R.framework/Versions/4.0/Resources/library/00LOCK-Seurat/00new/Seurat/libs
** R
** data
*** moving datasets to lazyload DB
/Library/Frameworks/R.framework/Resources/bin/INSTALL: line 34: 69964 Done                    echo 'tools:::.install_packages()'
     69965 Killed: 9               | R_DEFAULT_PACKAGES= LC_COLLATE=C "${R_HOME}/bin/R" $myArgs --no-echo --args ${args}
Error: Failed to install 'Seurat' from GitHub:
  (converted from warning) installation of package ‘/var/folders/g4/m3gngl812p72ck28fxxxrgcr0000gn/T//RtmpgdfQjI/file10615694955f5/Seurat_3.1.5.tar.gz’ had non-zero exit status

**Comment by mojaveazure** [comment]
The `Killed: 9` indicates there's an issue with the computer you're installing Seurat on, not necessarily with Seurat itself. Basically, your system is killing the installation process outside of R, which is not something we can easily debug. I would check to make sure you don't have any form of Conda installed on your system.

Also, why do you need the development version of Seurat to install on Shinyapps? That issue should have been resolved in the latest CRAN release.

**Comment by mmarchin** [comment]
I found this post when I was trying to figure out a shinyapps.io deployment failure, and I just wanted to chime in to say that 3.1.5 wasn't working for me, but the devel version (Seurat_3.1.5.9003) did.

**Comment by csimona** [comment]
my two cents: I had the same issue while loading Seurat (current stable version) from the command line in R (was working well on RStudio). I did have miniconda installed, but the issue didn't resolve after uninstalling it. It did finally resolve though after also removing r-miniconda from /Users/user/Lirbary/.

**Comment by msherafatian** [comment]
I have the same issue installing the development version of Seurat package. I also have the same issue installing Seurat wrappers. these are the errors I get from them: 

@@@@Development version of Seurat package:

*** moving datasets to lazyload DB
/Library/Frameworks/R.framework/Resources/bin/INSTALL: line 34: 80121 Done                    echo 'tools:::.install_packages()'
     80122 Killed: 9               | R_DEFAULT_PACKAGES= LC_COLLATE=C "${R_HOME}/bin/R" $myArgs --slave --args ${args}
Error: Failed to install 'Seurat' from GitHub:
  (converted from warning) installation of package ‘/var/folders/p7/yt9j9yt97y9760x0tlm06060rzv965/T//RtmpMsHM2Z/file12e9fdfe7eab/Seurat_3.2.0.9019.tar.gz’ had non-zero exit status

@@@@Seurat wrappers

Using github PAT from envvar GITHUB_PAT
Downloading GitHub repo satijalab/seurat-wrappers@HEAD
✓ checking for file ‘/private/var/folders/p7/yt9j9yt97y9760x0tlm06060rzv965/T/RtmpAIl0pB/remotes717b1bae243e/satijalab-seurat-wrappers-1a025ad/DESCRIPTION’ ...
─ preparing ‘SeuratWrappers’:
✓ checking DESCRIPTION meta-information ...
─ checking for LF line-endings in source and make files and shell scripts
─ checking for empty or unneeded directories
─ building ‘SeuratWrappers_0.2.0.tar.gz’
Warning: invalid uid value replaced by that for user 'nobody'
Warning: invalid gid value replaced by that for user 'nobody'

installing source package ‘SeuratWrappers’ ...
** using staged installation
** R
** byte-compile and prepare package for lazy loading
sh: line 1: 29819 Killed: 9 R_TESTS= '/Library/Frameworks/R.framework/Resources/bin/R' --no-save --slave 2>&1 < '/var/folders/p7/yt9j9yt97y9760x0tlm06060rzv965/T//RtmpfZCvaZ/file74744c823c9b'
ERROR: lazy loading failed for package ‘SeuratWrappers’
removing ‘/Library/Frameworks/R.framework/Versions/3.6/Resources/library/SeuratWrappers’
Error: Failed to install 'SeuratWrappers' from GitHub:
(converted from warning) installation of package ‘/var/folders/p7/yt9j9yt97y9760x0tlm06060rzv965/T//RtmpAIl0pB/file717b684eab93/SeuratWrappers_0.2.0.tar.gz’ had non-zero exit status
