### ISSUE TITLE
Error using FindAllMarkers and MAST

### ISSUE THREAD

**Issue by lizanyu** [satijalab/seurat#3496]
Hello! 

I am new to using Seurat and am trying to account for a metadata variable ("sample_name_numeric") when using `FindAllMarkers` in the following code:
```
FindAllMarkers(object = mfmo, latent.vars = "sample_name_numeric", test.use = "MAST", only.pos = T)
```
I get the following error message:
```
Calculating cluster 0
Assuming data assay in position 1, with name et is log-transformed.
                                                                                                                                                  
Done!
Combining coefficients and standard errors
Calculating log-fold changes
Calculating likelihood ratio tests
Calculating cluster 1
Assuming data assay in position 1, with name et is log-transformed.
                                                                                                                                                  
Done!
Combining coefficients and standard errors
Calculating log-fold changes
Calculating likelihood ratio tests
Calculating cluster 2
Assuming data assay in position 1, with name et is log-transformed.
                                                                                                                                                  
Done!
Combining coefficients and standard errors
Calculating log-fold changes
Calculating likelihood ratio tests
Calculating cluster 3
Assuming data assay in position 1, with name et is log-transformed.
                                                                                                                                                  
Done!
Combining coefficients and standard errors
Calculating log-fold changes
Calculating likelihood ratio tests
Calculating cluster 4
Assuming data assay in position 1, with name et is log-transformed.
                                                                                                                                                  
Done!
Combining coefficients and standard errors
Calculating log-fold changes
Calculating likelihood ratio tests
Calculating cluster 5
Assuming data assay in position 1, with name et is log-transformed.
                                                                                                                                                  
Done!
Combining coefficients and standard errors
Calculating log-fold changes
Calculating likelihood ratio tests
Calculating cluster 6
Assuming data assay in position 1, with name et is log-transformed.
                                                                                                                                                  
Done!
Combining coefficients and standard errors
Calculating log-fold changes
Calculating likelihood ratio tests
No DE genes identifiedThe following tests were not performed: When testing 0 versus all:
	error in evaluating the argument 'hypothesis' in selecting a method for function 'lrTest': invalid class “CoefficientHypothesis” object: superclass "characterORconnection" not defined in the environment of the object's classWhen testing 1 versus all:
	error in evaluating the argument 'hypothesis' in selecting a method for function 'lrTest': invalid class “CoefficientHypothesis” object: superclass "characterORconnection" not defined in the environment of the object's classWhen testing 2 versus all:
	error in evaluating the argument 'hypothesis' in selecting a method for function 'lrTest': invalid class “CoefficientHypothesis” object: superclass "characterORconnection" not defined in the environment of the object's classWhen testing 3 versus all:
	error in evaluating the argument 'hypothesis' in selecting a method for function 'lrTest': invalid class “CoefficientHypothesis” object: superclass "characterORconnection" not defined in the environment of the object's classWhen testing 4 versus all:
	error in evaluating the argument 'hypothesis' in selecting a method for function 'lrTest': invalid class “CoefficientHypothesis” object: superclass "characterORconnection" not defined in the environment of the object's classWhen testing 5 versus all:
	error in evaluating the argument 'hypothesis' in selecting a method for function 'lrTest': invalid class “CoefficientHypothesis” object: superclass "characterORconnection" not defined in the environment of the object's classWhen testing 6 versus all:
	error in evaluating the argument 'hypothesis' in selecting a method for function 'lrTest': invalid class “CoefficientHypothesis” object: superclass "characterORconnection" not defined in the environment of the object's class
```

The data is normalized and "sample_name_numeric" is a numeric variable. I don't understand this error message and couldn't find other posts to answer this question. Can you help me?? Thank you in advance for your help!

Liz

This is my sessionInfo:
```
R version 4.0.2 (2020-06-22)
Platform: x86_64-apple-darwin17.0 (64-bit)
Running under: macOS Mojave 10.14.6

Matrix products: default
BLAS:   /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/4.0/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
 [1] parallel  stats4    grid      stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
 [1] MAST_1.15.0                 scater_1.17.4               SingleCellExperiment_1.11.6 SummarizedExperiment_1.19.6 DelayedArray_0.15.7        
 [6] matrixStats_0.56.0          Matrix_1.2-18               Biobase_2.49.1              GenomicRanges_1.41.6        GenomeInfoDb_1.25.11       
[11] IRanges_2.23.10             S4Vectors_0.27.12           BiocGenerics_0.35.4         VennDiagram_1.6.20          futile.logger_1.4.3        
[16] plyr_1.8.6                  REdaS_0.9.3                 qdapTools_1.3.5             ggrepel_0.8.2               reshape_0.8.8              
[21] gplots_3.0.4                forcats_0.5.0               stringr_1.4.0               dplyr_1.0.2                 purrr_0.3.4                
[26] readr_1.3.1                 tidyr_1.1.2                 tibble_3.0.3                ggplot2_3.3.2               tidyverse_1.3.0            
[31] knitr_1.29                  Seurat_3.2.1               

loaded via a namespace (and not attached):
  [1] readxl_1.3.1              backports_1.1.9           igraph_1.2.5              lazyeval_0.2.2            splines_4.0.2            
  [6] BiocParallel_1.23.2       listenv_0.8.0             digest_0.6.25             htmltools_0.5.0           viridis_0.5.1            
 [11] gdata_2.18.0              fansi_0.4.1               magrittr_1.5              tensor_1.5                cluster_2.1.0            
 [16] ROCR_1.0-11               limma_3.45.13             globals_0.12.5            modelr_0.1.8              prettyunits_1.1.1        
 [21] colorspace_1.4-1          blob_1.2.1                rvest_0.3.6               haven_2.3.1               xfun_0.17                
 [26] crayon_1.3.4              RCurl_1.98-1.2            jsonlite_1.7.1            spatstat_1.64-1           spatstat.data_1.4-3      
 [31] survival_3.2-3            zoo_1.8-8                 glue_1.4.2                polyclip_1.10-0           gtable_0.3.0             
 [36] zlibbioc_1.35.0           XVector_0.29.3            leiden_0.3.3              BiocSingular_1.5.0        future.apply_1.6.0       
 [41] abind_1.4-5               scales_1.1.1              futile.options_1.0.1      DBI_1.1.0                 miniUI_0.1.1.1           
 [46] Rcpp_1.0.5                progress_1.2.2            viridisLite_0.3.0         xtable_1.8-4              reticulate_1.16          
 [51] rsvd_1.0.3                htmlwidgets_1.5.1         httr_1.4.2                RColorBrewer_1.1-2        ellipsis_0.3.1           
 [56] ica_1.0-2                 scuttle_0.99.13           pkgconfig_2.0.3           farver_2.0.3              uwot_0.1.8               
 [61] dbplyr_1.4.4              deldir_0.1-28             tidyselect_1.1.0          labeling_0.3              rlang_0.4.7              
 [66] reshape2_1.4.4            later_1.1.0.1             munsell_0.5.0             cellranger_1.1.0          tools_4.0.2              
 [71] cli_2.0.2                 generics_0.0.2            broom_0.7.0               ggridges_0.5.2            fastmap_1.0.1            
 [76] goftest_1.2-2             fs_1.5.0                  fitdistrplus_1.1-1        caTools_1.18.0            RANN_2.6.1               
 [81] pbapply_1.4-3             future_1.18.0             nlme_3.1-149              mime_0.9                  formatR_1.7              
 [86] xml2_1.3.2                compiler_4.0.2            rstudioapi_0.11           beeswarm_0.2.3            plotly_4.9.2.1           
 [91] png_0.1-7                 spatstat.utils_1.17-0     reprex_0.3.0              stringi_1.5.3             lattice_0.20-41          
 [96] vctrs_0.3.4               pillar_1.4.6              lifecycle_0.2.0           lmtest_0.9-38             BiocNeighbors_1.7.0      
[101] RcppAnnoy_0.0.16          data.table_1.13.0         cowplot_1.1.0             bitops_1.0-6              irlba_2.3.3              
[106] httpuv_1.5.4              patchwork_1.0.1           R6_2.4.1                  promises_1.1.1            KernSmooth_2.23-17       
[111] gridExtra_2.3             vipor_0.4.5               codetools_0.2-16          lambda.r_1.2.4            MASS_7.3-53              
[116] gtools_3.8.2              assertthat_0.2.1          chron_2.3-56              withr_2.2.0               sctransform_0.2.1        
[121] GenomeInfoDbData_1.2.3    mgcv_1.8-33               hms_0.5.3                 rpart_4.1-15              DelayedMatrixStats_1.11.1
[126] Rtsne_0.15                shiny_1.5.0               lubridate_1.7.9           ggbeeswarm_0.6.0         
```

**Comment by semmrich** [comment]
I have exactly the same issue, before v3.2.1 I never had any problems using MAST with 
`FindAllMarkers`
This is my command:
`S.ALL.markers <- FindAllMarkers(object = S.ALL, test.use = "MAST", only.pos = FALSE, logfc.threshold = log(2), min.pct = 0.25, verbose = TRUE, return.thresh = 0.05)`

session info:
```
R version 4.0.2 (2020-06-22)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 18363)

Matrix products: default

locale:
[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252    LC_MONETARY=English_United States.1252
[4] LC_NUMERIC=C                           LC_TIME=English_United States.1252    

attached base packages:
 [1] grid      parallel  stats4    stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
 [1] scmap_1.11.0                MAST_1.15.0                 Seurat_3.2.1                patchwork_1.0.1             DropletUtils_1.9.11        
 [6] scran_1.17.16               scater_1.17.4               tictoc_1.0                  hash_2.2.6.1                futile.matrix_1.2.7        
[11] gridExtra_2.3               gtable_0.3.0                rowr_1.1.3                  fgsea_1.15.0                VennDiagram_1.6.20         
[16] futile.logger_1.4.3         data.table_1.13.0           GSVA_1.37.4                 BBmisc_1.11                 tibble_3.0.3               
[21] readxl_1.3.1                ggplot2_3.3.2               gplots_3.0.4                dplyr_1.0.2                 SingleCellExperiment_1.11.6
[26] SummarizedExperiment_1.19.6 DelayedArray_0.15.7         matrixStats_0.56.0          Biobase_2.49.1              GenomicRanges_1.41.6       
[31] GenomeInfoDb_1.25.11        IRanges_2.23.10             S4Vectors_0.27.12           BiocGenerics_0.35.4         Matrix_1.3-0               

loaded via a namespace (and not attached):
  [1] reticulate_1.16           R.utils_2.10.1            tidyselect_1.1.0          RSQLite_2.2.0             AnnotationDbi_1.51.3     
  [6] htmlwidgets_1.5.1         BiocParallel_1.23.2       Rtsne_0.15                munsell_0.5.0             codetools_0.2-16         
 [11] ica_1.0-2                 statmod_1.4.34            future_1.18.0             miniUI_0.1.1.1            withr_2.2.0              
 [16] colorspace_1.4-1          rstudioapi_0.11           ROCR_1.0-11               tensor_1.5                listenv_0.8.0            
 [21] labeling_0.3              GenomeInfoDbData_1.2.3    polyclip_1.10-0           farver_2.0.3              bit64_4.0.5              
 [26] rhdf5_2.33.7              vctrs_0.3.4               generics_0.0.2            lambda.r_1.2.4            randomForest_4.6-14      
 [31] R6_2.4.1                  ggbeeswarm_0.6.0          rsvd_1.0.3                locfit_1.5-9.4            bitops_1.0-6             
 [36] rhdf5filters_1.1.2        spatstat.utils_1.17-0     promises_1.1.1            scales_1.1.1              beeswarm_0.2.3           
 [41] globals_0.12.5            goftest_1.2-2             rlang_0.4.7               splines_4.0.2             lazyeval_0.2.2           
 [46] checkmate_2.0.0           reshape2_1.4.4            abind_1.4-5               backports_1.1.9           httpuv_1.5.4             
 [51] tools_4.0.2               ellipsis_0.3.1            RColorBrewer_1.1-2        proxy_0.4-24              ggridges_0.5.2           
 [56] Rcpp_1.0.5                plyr_1.8.6                progress_1.2.2            lambda.tools_1.0.9        zlibbioc_1.35.0          
 [61] purrr_0.3.4               RCurl_1.98-1.2            prettyunits_1.1.1         rpart_4.1-15              deldir_0.1-28            
 [66] pbapply_1.4-3             viridis_0.5.1             cowplot_1.1.0             zoo_1.8-8                 ggrepel_0.8.2            
 [71] cluster_2.1.0             magrittr_1.5              RSpectra_0.16-0           futile.options_1.0.1      lmtest_0.9-38            
 [76] RANN_2.6.1                fitdistrplus_1.1-1        hms_0.5.3                 mime_0.9                  xtable_1.8-4             
 [81] XML_3.99-0.5              RMTstat_0.3               compiler_4.0.2            KernSmooth_2.23-17        crayon_1.3.4             
 [86] R.oo_1.24.0               htmltools_0.5.0           mgcv_1.8-33               later_1.1.0.1             tidyr_1.1.2              
 [91] DBI_1.1.0                 formatR_1.7               MASS_7.3-53               rappdirs_0.3.1            R.methodsS3_1.8.1        
 [96] gdata_2.18.0              igraph_1.2.5              pkgconfig_2.0.3           plotly_4.9.2.1            scuttle_0.99.13          
[101] annotate_1.67.1           vipor_0.4.5               dqrng_0.2.1               XVector_0.29.3            stringr_1.4.0            
[106] digest_0.6.25             sctransform_0.2.1         RcppAnnoy_0.0.16          graph_1.67.1              spatstat.data_1.4-3      
[111] cellranger_1.1.0          leiden_0.3.3              fastmatch_1.1-0           uwot_0.1.8                edgeR_3.31.4             
[116] googleVis_0.6.6           DelayedMatrixStats_1.11.1 GSEABase_1.51.1           shiny_1.5.0               gtools_3.8.2             
[121] lifecycle_0.2.0           nlme_3.1-149              jsonlite_1.7.1            Rhdf5lib_1.11.3           BiocNeighbors_1.7.0      
[126] viridisLite_0.3.0         limma_3.45.13             pillar_1.4.6              lattice_0.20-41           fastmap_1.0.1            
[131] httr_1.4.2                survival_3.2-3            glue_1.4.2                spatstat_1.64-1           png_0.1-7                
[136] bluster_0.99.1            bit_4.0.4                 class_7.3-17              stringi_1.5.3             HDF5Array_1.17.3         
[141] blob_1.2.1                BiocSingular_1.5.0        caTools_1.18.0            memoise_1.1.0             e1071_1.7-3              
[146] irlba_2.3.3               future.apply_1.6.0       
```

Many Thanks for maintaining this package!
Stephan

**Comment by timoast** [comment]
I was able to reproduce this issue when including a latent variable in the function call. For example:

```r
library(SeuratData)
library(Seurat)

data("panc8")
Idents(panc8) <- "celltype"
panc8 <- UpdateSeuratObject(panc8)

# fails
markers <- FindAllMarkers(
  object = panc8,
  latent.vars = "tech",
  test.use = "MAST",
  only.pos = TRUE
)

# works
markers <- FindAllMarkers(
  object = panc8,
  test.use = "MAST",
  only.pos = TRUE
)
```

We will work on a fix

**Comment by semmrich** [comment]
Just posted my reprex for #3551, using that data with
```
blood.query.integrated$datasets <- Idents(blood.query.integrated)
Idents(blood.query.integrated) <- blood.query.integrated$predicted.id
blood.markers <- FindAllMarkers(object = blood.query.integrated, test.use = "MAST", only.pos = FALSE, logfc.threshold = log(2), min.pct = 0.25, verbose = TRUE, return.thresh = 0.05)
``` 
worked like a charm!? And the difference was... MAST package version 1.14.0, vs my earlier post here and @lizanyu using 1.15.0

**Comment by LuciaJim** [comment]
Hello! Indeed I have the same issue when running `test.use = "MAST"` with `latent.vars`. If no `latent.vars` are selected it runs fine. Do you know how to overcome it?
PS: By any chance does anyone know if the same problem appears if `test.use = "LR"` with `latent.vars`? (it takes time to run them all). Thanks!

**Comment by GBeattie** [comment]
Not sure if this will fix it for everyone (I was getting an almost identical error without using the latent.vars option). I also had issues updating my MAST to 1.16 (from 1.14) using BiocManager (would only install 1.14). I instead installed from the 1.16 TAR archive, and now it's working fine (in R 4.0.3). Worth a shot for those using latent.vars.

**Comment by khajdarovic** [comment]
Hi I had the same issue (even when not using latent.vars). I also updated to MAST 1.16 and restarted RStudio, and the issue is now resolved. I also had to install via TAR as the bioconductor update only updates to 1.14.

**Comment by semmrich** [comment]
Same for me: with MAST 1.16.0 and Seurat 3.9.9.9010 the issue is resolved, it finds the markers again as before.
Best option for FindAllMarkers imho 8)

**Comment by amberbangma** [comment]
I also have this issue! My Biocmanager only installs 1.14. How do I install the newer versions?

**Comment by denvercal1234GitHub** [comment]
Could anyone be so kind helping to understand how you select which test to use for FindAllMarkers()? It guess it depends on the data distribution, but other than that, did you have any more insights or resources I can take a look? Thank you so much!

**Comment by mr-september** [comment]
I have just ran into this issue. However, installing MAST 1.16 from `tar.gz` and restarting R did not fix this, even with a completely clean environment. Any other possible solutions?

**Comment by itraniello** [comment]
I am also having issues running MAST with the following command. As an example:

```
FindMarkers(obj, ident.1 = "control_1", ident.2 = "treatment_1", test.use = "MAST")
Error in MatrixGenerics:::.load_next_suggested_package_to_search(x) : 
  Failed to find a rowRanges() method for SingleCellExperiment objects.
```

I have tried updating to 1.16 then downgrading MAST (currently switched to an older version, see below) and DefaultAssay is set to "RNA." This worked a few months ago but I'm not comprehending this error. Any ideas?

Thanks!
```

> sessionInfo()
R version 4.0.4 (2021-02-15)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 19042)

Matrix products: default

locale:
[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252    LC_MONETARY=English_United States.1252 LC_NUMERIC=C                          
[5] LC_TIME=English_United States.1252    

attached base packages:
[1] parallel  stats4    stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
 [1] scater_1.16.2               ggplot2_3.3.3               MAST_1.10.0                 SingleCellExperiment_1.10.1 SummarizedExperiment_1.18.2 DelayedArray_0.16.1        
 [7] MatrixGenerics_1.2.1        matrixStats_0.58.0          Matrix_1.2-18               Biobase_2.48.0              GenomicRanges_1.40.0        GenomeInfoDb_1.24.2        
[13] IRanges_2.24.1              S4Vectors_0.28.1            BiocGenerics_0.36.0         SeuratObject_4.0.0          Seurat_4.0.0               

loaded via a namespace (and not attached):
  [1] ggbeeswarm_0.6.0          minqa_1.2.4               Rtsne_0.15                colorspace_2.0-0          deldir_0.2-9              ellipsis_0.3.1           
  [7] ggridges_0.5.3            XVector_0.28.0            BiocNeighbors_1.6.0       spatstat.data_2.0-0       leiden_0.3.7              listenv_0.8.0            
 [13] ggrepel_0.9.1             fansi_0.4.2               sparseMatrixStats_1.0.5   codetools_0.2-18          splines_4.0.4             polyclip_1.10-0          
 [19] jsonlite_1.7.2            nloptr_1.2.2.2            ica_1.0-2                 cluster_2.1.0             png_0.1-7                 uwot_0.1.10              
 [25] shiny_1.6.0               sctransform_0.3.2         compiler_4.0.4            httr_1.4.2                assertthat_0.2.1          fastmap_1.1.0            
 [31] lazyeval_0.2.2            limma_3.44.3              BiocSingular_1.4.0        later_1.1.0.1             htmltools_0.5.1.1         tools_4.0.4              
 [37] rsvd_1.0.3                igraph_1.2.6              gtable_0.3.0              glue_1.4.2                GenomeInfoDbData_1.2.3    RANN_2.6.1               
 [43] reshape2_1.4.4            dplyr_1.0.4               tinytex_0.29              Rcpp_1.0.6                spatstat_1.64-1           scattermore_0.7          
 [49] vctrs_0.3.6               nlme_3.1-152              DelayedMatrixStats_1.10.1 lmtest_0.9-38             xfun_0.21                 stringr_1.4.0            
 [55] globals_0.14.0            lme4_1.1-26               mime_0.10                 miniUI_0.1.1.1            lifecycle_1.0.0           irlba_2.3.3              
 [61] statmod_1.4.35            goftest_1.2-2             future_1.21.0             MASS_7.3-53.1             zlibbioc_1.34.0           zoo_1.8-8                
 [67] scales_1.1.1              promises_1.2.0.1          spatstat.utils_2.0-0      RColorBrewer_1.1-2        reticulate_1.18           pbapply_1.4-3            
 [73] gridExtra_2.3             rpart_4.1-15              stringi_1.5.3             blme_1.0-5                BiocParallel_1.22.0       boot_1.3-27              
 [79] rlang_0.4.10              pkgconfig_2.0.3           bitops_1.0-6              lattice_0.20-41           ROCR_1.0-11               purrr_0.3.4              
 [85] tensor_1.5                patchwork_1.1.1           htmlwidgets_1.5.3         cowplot_1.1.1             tidyselect_1.1.0          parallelly_1.23.0        
 [91] RcppAnnoy_0.0.18          plyr_1.8.6                magrittr_2.0.1            R6_2.5.0                  generics_0.1.0            DBI_1.1.1                
 [97] withr_2.4.1               pillar_1.5.0              mgcv_1.8-33               fitdistrplus_1.1-3        survival_3.2-7            abind_1.4-5              
[103] RCurl_1.98-1.2            tibble_3.0.6              future.apply_1.7.0        crayon_1.4.1              KernSmooth_2.23-18        utf8_1.1.4               
[109] plotly_4.9.3              viridis_0.5.1             grid_4.0.4                data.table_1.14.0         digest_0.6.27             xtable_1.8-4             
[115] tidyr_1.1.2               httpuv_1.5.5              munsell_0.5.0             beeswarm_0.2.3            viridisLite_0.3.0         vipor_0.4.5  
```

**Comment by rsatija** [comment]
Closing this issue as it is related to MAST, and is fized in the latest version.
