### ISSUE TITLE
2 errors when using FindTransferAnchors() and MapQuery()

### ISSUE THREAD

**Issue by malihhhh** [satijalab/seurat#3615]
Hello,
I am trying to integrate one query data(about 40000 cells) to a reference data(about 50000 cells), following vignette: [Mapping scRNA-seq queries onto reference datasets](https://satijalab.org/seurat/v4.0/reference_mapping.html). I have the version of R(4.0.2) and seruat(Seurat_3.9.9.9002). I want to see the query data's distribution in the reference data set of the clusters, and how many cells are in each cluster. The query data and reference data have been normalized with NormalizeData()  "LogNormalize" and ScaleData(). In addition to these, the reference data set has also undergone PCA dimensionality reduction and clustering, RunUMAP() and RunTSNE() as done. However, when using FindTransferAnchors() and MapQuery(),  I get a couple of errors:
`Projecting cell embeddings
Finding neighborhoods
Finding anchors
        Found 99871 anchors
Filtering anchors
        Retained 26067 anchors
Finding integration vectors
Finding integration vector weights
0%   10   20   30   40   50   60   70   80   90   100%
[----|----|----|----|----|----|----|----|----|----|
**************************************************|
Transfering 15935 features onto reference dat
Integrating dataset 2 with reference dataset
Finding integration vectors
Error in h(simpleError(msg, call)) :
  error in evaluating the argument 'x' in selecting a method for function 't': subscript out of bounds
Calls: MapQuery ... FindIntegrationMatrix -> t -> .handleSimpleError -> h
In addition: Warning message:
In CheckDuplicateCellNames(object.list = objects) :
  Some cell names are duplicated across objects provided. Renaming to enforce unique cell names.
Execution halted`
These is my code:
`pbmc.com <- readRDS(file = "query.rds")

reference <- readRDS(file = '/data/share/zhangyl/pbmc_com_1k')

anchors <- FindTransferAnchors(reference = reference,query = pbmc.com,normalization.method ="LogNormalize",reference.reduction = "pca", dims = 1:10)

pbmc.com <- MapQuery(anchorset = anchors,query = pbmc.com,reference = reference,refdata = "RNA",reference.reduction ="pca", reduction.model = "umap")
`
When I encountered this error for the first time, I changed the cells name of the query data set, but it didn't work. I don't know what went wrong, please help me, thanks！

**Comment by andrewwbutler** [comment]
Hi,

Thanks for reporting. I believe we've fixed this bug now if you try installing the latest `release/4.0.0` branch (should see version Seurat_3.9.9.9003). Please update and let us know that resolves the issue.

**Comment by malihhhh** [comment]
Hello,
I try to install it by  remotes::install_github("satijalab/seurat", ref = "release/4.0.0",force = TRUE). But when everything is done, with no wrong. I got nothing. sessionInfo() shows the version is Seurat_3.9.9.9003, which was installed by my teacher when I asked him to install 4.0. It is hard to install it.
But I can use these functions, and When refactoring the variable (query) with a completely different name I did not see this error. 
But I get a new one:
`Error: The provided reduction.model does not have a model stored. Please try running umot-learn on the object first`
I am confused because the reference set has gone through RunUMAP()

**Comment by cdarby** [comment]
The error you see now is because the reference does not have a UMAP model. Use the "return.model=TRUE" parameter in RunUMAP. You may find the vignette on this topic helpful: https://satijalab.org/seurat/v4.0/reference_mapping.html

**Comment by Yale73** [comment]
@cdarby Hi， I ran the RunUMAP with "return.model=TRUE", but still get the error. I also used the latest Seurat version.
`Error: The provided reduction.model does not have a model stored. Please try running umot-learn on the object first`

Thanks,
Yale

**Comment by andrewwbutler** [comment]
Hi @Yale73 ,

If the error persists, could you open a new issue with some more details about what you ran prior to getting this error and if possible a reproducible example?

**Comment by iva302** [comment]
> Hi @andrewwbutler,
> 
> The error appears again and again and I have opened a new issue.
> 
> Thanks, Yale

Hello,
Were you able to resolve this error?
Thank you,
I.

**Comment by pmjklemm** [comment]
`return.model=TRUE` in RunUmap fixed it for me (I am on Seurat v4.1.0)
