### ISSUE TITLE
batch_var option broken in SCtransform 

### ISSUE THREAD

**Issue by ashupars** [satijalab/seurat#3925]
Hello I am having issues running the batch_variable option in Sctransform. All was working well until about a week back when the function stopped working potentially after a restart of R studio. As I have already processed several datasets using this function it would be nice to get it back working! 

When I run the SCTransform function with the "batch_var" included....

 Celltype_SCT <- SCTransform(Celltype_SCT, batch_var = "Experiment", variable.features.n = 400, return.only.var.genes = FALSE)_

It throws this error...

_Error in is.nan(rel_attr) : 
  default method not implemented for type 'list'_

Running SCT transform without the "batch_var" works completely fine. Additionally until recently running SCTransform with "batch_var" was working completely fine with the same metadata so it is not an issue with the metadata input. 

Has this feature been removed from SCTransform? Any help would be greatly appreciated thanks! 

-Andrew 
Scripps Research

**Comment by ChristophH** [comment]
No, this feature has not been removed. The error you see is due to a known bug in the latest version of the sctransform package. It's fixed in the develop branch which you can install via `remotes::install_github("ChristophH/sctransform@develop")`

**Comment by ashupars** [comment]
Great thanks that worked!

**Comment by Winbuntu** [comment]
@ChristophH I had the same problem, but after I updating sctransfrom as described above, a new error message came out:

![image](https://user-images.githubusercontent.com/11471267/110548661-e8294780-80fe-11eb-8bef-c45e02237469.png)

The model string does not looks right to me.. Would you mind  @doublechecking this?

**Comment by ms-gx** [comment]
Same problem as above!

**Comment by plijnzaad** [comment]
This bug is still there in Seurat 4.1.0. I looks like by default, `orig.ident` is always taken along as the `batch_var`, which makes perfect sense but I haven't seen it documented (and how would one overrule this default if needed?).
