### ISSUE TITLE
SpatialPlot crop = FALSE changes "aspect ratio" of coordinates, also misaligns image to plot

### ISSUE THREAD

**Issue by InternetExplorerBoy** [satijalab/seurat#4411]
Dear Seurat team,

I have recently started using the Seurat package and I greatly appreciate the user-friendliness and the excellent documentation/vigenttes you provide. As a fresh graduate with a BSc in Biology, I am quite new to R and I have never analyzed high-throughput data before. Thanks to Seurat I could learn a lot about scRNA sequencing and spatial transcriptomics on my own.

I am running into the same (or at least similar) bug as reported in #2700 last year. That one turned out to be related with a ggplot2 update and it got immediately fixed. A few days ago @JoyOtten opened issue #4394, however from the image provided I wasn't quite sure whether it is the same issue as I am facing right now.

**My issue is the following:**
When setting crop = FALSE in the SpatialPlot() function, the plot sometimes is misaligned with respect to the background image (see left image below). In some samples, however the image aligns perfectly with the plot. When I added the coordinate system, I noticed that the units on the x-axis got "compressed" with respect to the y-axis, i.e. the "aspect ratio" is no longer equal to 1 (see right image below). Therefore, the whole plot appears distorted, forming a rectangle, rather than a square.

![Example_CropFALSE](https://user-images.githubusercontent.com/60901344/116253018-63f35800-a770-11eb-9d67-e75e9b6bf47f.png)

When setting crop = TRUE, I get the expected plot, with no distortion and no misalignment of the image (see image below).

![Example_CropTRUE](https://user-images.githubusercontent.com/60901344/116254753-e6304c00-a771-11eb-8b94-44f553414dbd.png)

Digging a bit deeper into the function, I came across a ggproto object called geom_spatial(), which I believe is responsible of aligning the plot to the image. Maybe the bug could be caused by a missing coord_fixed(), since the "aspect ratio" gets distorted?

I would be very greatful if the Seurat developpers would address this issue shortly.

I was able to reproduce the bug with the stxBrain dataset from the spatial transcriptomics vignette, however, the misalignment appears to be less strong in that case and the change in aspect ratio is unnoticeable by human eye (see image below; crop = FALSE [left]; crop = TRUE [right]).
Nevertheless, I hope it helps to fix the bug.

![ReproducibleExample](https://user-images.githubusercontent.com/60901344/116258546-55f40600-a775-11eb-99c6-d6e6ac55a2c5.png)

**Reproducible Example Code:**
```r
library(Seurat)
library(SeuratData)
library(ggplot2)

InstallData("stxBrain")

brain <- LoadData("stxBrain", type = "anterior1")

brain <- SCTransform(brain, assay = "Spatial", verbose = FALSE)
brain <- RunPCA(brain, assay = "SCT", verbose = FALSE)
brain <- FindNeighbors(brain, reduction = "pca", dims = 1:30)
brain <- FindClusters(brain, verbose = FALSE)
brain <- RunUMAP(brain, reduction = "pca", dims = 1:30)

plot <- SpatialDimPlot(brain, crop = FALSE, label = TRUE, label.size = 3) +
  theme_minimal()
plot
```

Thank you in advance for your effort.

**Session Info:**
```r
> sessionInfo()
R version 4.0.5 (2021-03-31)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 20.04.1 LTS

Matrix products: default
BLAS:   /usr/lib/x86_64-linux-gnu/blas/libblas.so.3.9.0
LAPACK: /usr/lib/x86_64-linux-gnu/lapack/liblapack.so.3.9.0

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C               LC_TIME=de_CH.UTF-8       
 [4] LC_COLLATE=en_US.UTF-8     LC_MONETARY=de_CH.UTF-8    LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=de_CH.UTF-8       LC_NAME=C                  LC_ADDRESS=C              
[10] LC_TELEPHONE=C             LC_MEASUREMENT=de_CH.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] cowplot_1.1.1             here_1.0.1                dplyr_1.0.5              
[4] patchwork_1.1.1           ggplot2_3.3.0             stxBrain.SeuratData_0.1.1
[7] SeuratData_0.2.1          SeuratObject_4.0.0        Seurat_4.0.1             

loaded via a namespace (and not attached):
  [1] nlme_3.1-152          matrixStats_0.58.0    spatstat.sparse_2.0-0
  [4] RcppAnnoy_0.0.18      RColorBrewer_1.1-2    httr_1.4.2           
  [7] rprojroot_2.0.2       sctransform_0.3.2     tools_4.0.5          
 [10] utf8_1.2.1            R6_2.5.0              irlba_2.3.3          
 [13] rpart_4.1-15          KernSmooth_2.23-18    uwot_0.1.10          
 [16] mgcv_1.8-33           lazyeval_0.2.2        colorspace_2.0-0     
 [19] withr_2.4.2           tidyselect_1.1.0      gridExtra_2.3        
 [22] compiler_4.0.5        cli_2.4.0             plotly_4.9.3         
 [25] labeling_0.4.2        scales_1.1.1          lmtest_0.9-38        
 [28] spatstat.data_2.1-0   ggridges_0.5.3        pbapply_1.4-3        
 [31] rappdirs_0.3.3        goftest_1.2-2         stringr_1.4.0        
 [34] digest_0.6.27         spatstat.utils_2.1-0  pkgconfig_2.0.3      
 [37] htmltools_0.5.1.1     parallelly_1.24.0     fastmap_1.1.0        
 [40] htmlwidgets_1.5.3     rlang_0.4.10          rstudioapi_0.13      
 [43] shiny_1.6.0           farver_2.1.0          generics_0.1.0       
 [46] zoo_1.8-9             jsonlite_1.7.2        ica_1.0-2            
 [49] magrittr_2.0.1        Matrix_1.3-2          Rcpp_1.0.6           
 [52] munsell_0.5.0         fansi_0.4.2           abind_1.4-5          
 [55] reticulate_1.19       lifecycle_1.0.0       stringi_1.5.3        
 [58] MASS_7.3-53.1         Rtsne_0.15            plyr_1.8.6           
 [61] grid_4.0.5            parallel_4.0.5        listenv_0.8.0        
 [64] promises_1.2.0.1      ggrepel_0.9.1         crayon_1.4.1         
 [67] miniUI_0.1.1.1        deldir_0.2-10         lattice_0.20-41      
 [70] splines_4.0.5         tensor_1.5            pillar_1.6.0         
 [73] igraph_1.2.6          spatstat.geom_2.1-0   future.apply_1.7.0   
 [76] reshape2_1.4.4        codetools_0.2-18      leiden_0.3.7         
 [79] glue_1.4.2            data.table_1.14.0     vctrs_0.3.7          
 [82] png_0.1-7             httpuv_1.5.5          gtable_0.3.0         
 [85] RANN_2.6.1            purrr_0.3.4           spatstat.core_2.1-2  
 [88] polyclip_1.10-0       tidyr_1.1.3           scattermore_0.7      
 [91] future_1.21.0         xfun_0.22             mime_0.10            
 [94] xtable_1.8-4          RSpectra_0.16-0       later_1.1.0.1        
 [97] survival_3.2-10       viridisLite_0.4.0     tibble_3.1.1         
[100] tinytex_0.31          cluster_2.1.1         globals_0.14.0       
[103] fitdistrplus_1.1-3    ellipsis_0.3.1        ROCR_1.0-11
```

**Comment by andrewwbutler** [comment]
Hi @InternetExplorerBoy ,

We've pushed a fix for the example you provided to the `develop` branch. If you could try installing that (instructions [here](https://satijalab.org/seurat/articles/install.html#install-the-development-version-of-seurat-1)) and seeing if that resolves your issue?

In the case of your reproducible example, the offset problem was actually caused by the labeling and that's where we implemented the fix. However, if your first example it doesn't seem like you added labels so if this fix doesn't solve it there, let us know.

**Comment by InternetExplorerBoy** [comment]
Dear @andrewwbutler ,

Thank you very much for looking into it. I've installed the `develop` branch of Seurat and put it to a test with the `stxBrain` dataset and my project dataset.

For the `stxBrain` dataset, the issue seems to be fixed, in both cases where `label = TRUE` and `label = FALSE`.

For my current project dataset however, the issue still persists, since it was unrelated to the labelling (see image below).

![Test](https://user-images.githubusercontent.com/60901344/117543550-9a0cc380-b01d-11eb-8b8e-065b747ba85e.png)

As you might have noticed, some spots have been removed since my last post, due to stricter filtering during QC. Now the distortion of the image is even more extreme. My guess is, that the distortion increases, the smaller the percentage of the capture area covered by the tissue or a combination of the shape of the tissue and its location within the capture area. In order to demonstrate what I mean by this, please take a look at the following images.

![Test2](https://user-images.githubusercontent.com/60901344/117544289-0c32d780-b021-11eb-9ace-62b53db77ab4.png)

From the images in the first and second row, we can see how the shape of the tissue determines the direction, in which the coordinates are stretched. In the images of the third row, 2 tissue sections have been placed in two opposing corners of the capture area. There is only little distortion of the coordinates, and the spots align nicely to the image. However in the following example there is little to no distortion, but the spots fail to align to the image nevertheless. Maybe coordinate distortion and spot alignment are two unrelated issues?

![Test3](https://user-images.githubusercontent.com/60901344/117545070-8c0e7100-b024-11eb-8aba-dca802cf7a3c.png)

Unfortunately, I can not share the data publicly on github, but if it's necessary in order to fix this issue I could possibly share the .rds file with you.

Thank you very much for your effort.

**Comment by andrewwbutler** [comment]
Thanks for testing. I had a feeling it wouldn't resolve the issue for your data. If you are able to share the data, that would be very helpful for debugging this further (you can send to abutler@nygenome.org). Feel free to remove any of the actual expression/metadata info as well if that's a concern as it's not particularly relevant to this issue.

**Comment by andrewwbutler** [comment]
Thanks for sending some test data. I've pushed another fix to the develop branch that should fix your issue. Please try re-installing and see if that resolves it.

**Comment by InternetExplorerBoy** [comment]
Dear @andrewwbutler,

Fantastic work! Thank you very much for the fix. The plots look very neat and now one can use a consistent `pt.size.factor` across the different samples.

Keep up the great work!
Kind regards,
InternetExplorerBoy
