### ISSUE TITLE
Error in match.arg(arg = layer, choices = Layers(object = object, search = FALSE)) :    'arg' should be one of “counts”, “data”, “scale.data”

### ISSUE THREAD

**Issue by levinhein** [satijalab/seurat#7451]
Hello. Is there a current bug/issue regarding this error? I'm currently seeing others experiencing this and I also encountered it now. 
```

Error in match.arg(arg = layer, choices = Layers(object = object, search = FALSE)) : 
  'arg' should be one of “counts”, “data”, “scale.data”

```
![image](https://github.com/satijalab/seurat/assets/68268222/c7bc0a17-ceea-4bdb-b9d1-7b61fdcb3256)

"KD.list" is a list of seurat objects. There seems to be "2 layers" which I am not familiar of how to use or if it should be used.
![image](https://github.com/satijalab/seurat/assets/68268222/60d71f5e-8c76-4762-a6b8-a0c540d2e79c)

I have tried other suggestions in other threads like restarting RStudio, re-installing seurat, re-installing irlba, and setting `DefaultAssay(seurat.object) <- "RNA"` but to no avail. All of the datasets have >600 cells. 

Could you please help me how I can resolve this issue? This never happened to me before. When the seurat v5 was released, I installed it, encountered errors, and so reverted back to version 4.3.0 in hopes of having no issues like before. But even if I went back to v4.3.0, I now encounter the same error. When I packageVersion("Seurat"), the version is indeed v4.3.0.

Thank you!

**Comment by levinhein** [comment]
Now, I followed the suggestion in https://github.com/satijalab/seurat/issues/7182 

The Error in match.arg() vanished, but the error changed to this:

```
Error in irlba(A = t(x = object), nv = npcs, ...) : 
  BLAS/LAPACK routine 'DLASCL' gave error code -4
```
 
![image](https://github.com/satijalab/seurat/assets/68268222/0237bc54-2a66-4c9a-aeb2-83fb3eb65bcd)

**Comment by levinhein** [comment]
Finally, for others who experience the same issue but other solutions didn't work, maybe you can try this:
I tried the suggestion of https://github.com/satijalab/seurat/issues/1788#issuecomment-966397696

I changed the npcs parameter value in RunPCA. The default of RunPCA is npcs =50. At first, I tried npcs = 49 and I still encountered the same error. When I tried adjusting to lower npcs = 40, it worked, so I used this number.

Since my irlba package is updated, maybe the issue is in RunPCA function?

**Comment by longmanz** [comment]
Hi, 
I think the 1st problem you saw was fixed by https://github.com/satijalab/seurat/issues/7182. 
And the 2nd one is a different issue, caused by the RunPCA(). 
Does this issue happen to all your seurat objects in your KD.list or just one/a few of them?

**Comment by levinhein** [comment]
Hi @longmanz Indeed the issue is from RunPCA(). After trying each, it does happen on all of the Seurat objects. 

Here's the code I used from beginning up to the error point when testing each data:


```
data <- Read10X("/mnt/RAID_5/vincent/Project-COVID/Data-COVID-GSE157344/1/")
#Create Seurat object. 
COVID15 <- CreateSeuratObject(counts = data, project = "COVID15", min.cells = 3, min.features = 100) #note: we lowered the min.features to 100 as this is now the recommendation when studying neutrophils
#Standard pre-processing workflow
COVID15[["percent.mt"]] <- PercentageFeatureSet(COVID15, pattern = "^MT-") 
COVID15[["percent.hb"]] <- PercentageFeatureSet(COVID15, pattern = "^HB") 
COVID15[["percent.rb"]] <- PercentageFeatureSet(COVID15, pattern = "^RP[SL][[:digit:]]|^RPLP[[:digit:]]|^RPSA")
### SUB-SETTING
COVID15 <- subset(COVID15, subset = nFeature_RNA > 100 & nFeature_RNA < 5000 & percent.mt < 10)
#Removal of RB, HB, MALAT1, MT genes # NOTE: According to a Nature paper, they removed rb genes. Another reference is: 
COVID15 <- COVID15[!grepl("^MT-", rownames(COVID15)), ] 
COVID15 <- COVID15[!grepl("MALAT1", rownames(COVID15)), ]
COVID15 <- COVID15[!grepl("XIST", rownames(COVID15)), ]
COVID15 <- COVID15[!grepl("RSP4Y1 ", rownames(COVID15)), ]

COVID15 <- AddMetaData(object = COVID15, metadata = "COVID", col.name = "group") 

DefaultAssay(COVID15) <- "RNA"
dim(COVID15)   #[1] 14814  1465

COVID15<-NormalizeData(COVID15, verbose = TRUE)
COVID15<-FindVariableFeatures(COVID15, selection.method = "vst", nfeatures=3000, verbose = TRUE)
COVID15<-ScaleData(COVID15, features = rownames(COVID15), verbose = TRUE)
COVID15<-RunPCA(COVID15, verbose = TRUE)
```


ERROR
```
Error in irlba(A = t(x = object), nv = npcs, ...) : 
  BLAS/LAPACK routine 'DLASCL' gave error code -4
```
SESSION INFORMATION
```
> sessionInfo()
R version 4.3.0 (2023-04-21)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 23.04

Matrix products: default
BLAS/LAPACK: /usr/lib/x86_64-linux-gnu/libmkl_rt.so;  LAPACK version 3.8.0

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C               LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8     LC_MONETARY=en_US.UTF-8   
 [6] LC_MESSAGES=en_US.UTF-8    LC_PAPER=en_US.UTF-8       LC_NAME=C                  LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

time zone: Asia/Taipei
tzcode source: system (glibc)

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
 [1] viridis_0.6.3           viridisLite_0.4.2       writexl_1.4.2           RColorBrewer_1.1-3      lubridate_1.9.2        
 [6] forcats_1.0.0           stringr_1.5.0           purrr_1.0.1             readr_2.1.4             tibble_3.2.1           
[11] tidyverse_2.0.0         ggpubr_0.6.0            tidyr_1.3.0             data.table_1.14.8       Matrix_1.5-4.1         
[16] patchwork_1.1.2         ggplot2_3.4.2           cowplot_1.1.1           dplyr_1.1.2             plyr_1.8.8             
[21] Seurat_4.9.9.9049       SeuratObject_4.9.9.9085 sp_1.6-1               

loaded via a namespace (and not attached):
  [1] rstudioapi_0.14        jsonlite_1.8.5         magrittr_2.0.3         ggbeeswarm_0.7.2       spatstat.utils_3.0-3  
  [6] farver_2.1.1           vctrs_0.6.3            ROCR_1.0-11            spatstat.explore_3.2-1 rstatix_0.7.2         
 [11] htmltools_0.5.5        broom_1.0.5            sctransform_0.3.5      parallelly_1.36.0      KernSmooth_2.23-21    
 [16] htmlwidgets_1.6.2      ica_1.0-3              plotly_4.10.2          zoo_1.8-12             igraph_1.5.0          
 [21] mime_0.12              lifecycle_1.0.3        pkgconfig_2.0.3        R6_2.5.1               fastmap_1.1.1         
 [26] fitdistrplus_1.1-11    future_1.32.0          shiny_1.7.4            digest_0.6.31          colorspace_2.1-0      
 [31] tensor_1.5             RSpectra_0.16-1        irlba_2.3.5.1          labeling_0.4.2         progressr_0.13.0      
 [36] fansi_1.0.4            spatstat.sparse_3.0-1  timechange_0.2.0       httr_1.4.6             polyclip_1.10-4       
 [41] abind_1.4-5            compiler_4.3.0         withr_2.5.0            backports_1.4.1        carData_3.0-5         
 [46] fastDummies_1.6.3      ggsignif_0.6.4         MASS_7.3-60            tools_4.3.0            vipor_0.4.5           
 [51] lmtest_0.9-40          beeswarm_0.4.0         httpuv_1.6.11          future.apply_1.11.0    goftest_1.2-3         
 [56] glue_1.6.2             nlme_3.1-162           promises_1.2.0.1       grid_4.3.0             Rtsne_0.16            
 [61] cluster_2.1.4          reshape2_1.4.4         generics_0.1.3         gtable_0.3.3           spatstat.data_3.0-1   
 [66] tzdb_0.4.0             hms_1.1.3              car_3.1-2              utf8_1.2.3             spatstat.geom_3.2-1   
 [71] RcppAnnoy_0.0.20       ggrepel_0.9.3          RANN_2.6.1             pillar_1.9.0           spam_2.9-1            
 [76] RcppHNSW_0.4.1         later_1.3.1            splines_4.3.0          lattice_0.21-8         survival_3.5-5        
 [81] deldir_1.0-9           tidyselect_1.2.0       miniUI_0.1.1.1         pbapply_1.7-0          gridExtra_2.3         
 [86] scattermore_1.2        matrixStats_1.0.0      stringi_1.7.12         lazyeval_0.2.2         codetools_0.2-19      
 [91] cli_3.6.1              uwot_0.1.14            xtable_1.8-4           reticulate_1.30        munsell_0.5.0         
 [96] Rcpp_1.0.10            globals_0.16.2         spatstat.random_3.1-5  png_0.1-8              ggrastr_1.0.2         
[101] parallel_4.3.0         ellipsis_0.3.2         dotCall64_1.0-2        listenv_0.9.0          scales_1.2.1          
[106] ggridges_0.5.4         leiden_0.4.3           rlang_1.1.1           
```

**Comment by levinhein** [comment]
Note that the same thing now happens to previous data from a study that I already finished which was conducted in the previous Seurat version successfully.

This error now only started happening after I installed Seurat version 5 (Seurat_4.9.9.9049).

**Comment by Gesmira** [comment]
Hi, are you able to share a smaller reproducible example?

**Comment by levinhein** [comment]
Hi @Gesmira 

Here's a sample of the data that I analyzed:
https://drive.google.com/file/d/1bpmHY_AhJ0Dvjuaq5FSbWgC2S4MZowMj/view?usp=sharing

Other notes:
1. This data is public data I recently downloaded
2. I recently updated to v5
4. Even the previous project that I already completed and submitted for publication, no longer works appropriately now. Same error is still encountered specifically in RunPCA error in irlba() ... BLAS/LAPACK routine 'DLASCL' gave error code -4   
5. I reverted to my previous Seurat version 4.3.0 with hopes that it will go back to my previous normal runs, but the problem persisted
6. Our lab's admin re-installed the R,  r-core and r-core-base, but still the same error persisted.
7. Again, I re-analyzed my previous completed project and the recently downloaded public data, and still the problem persists. 
8. When other people does it on their own (https://github.com/satijalab/seurat/issues/7457), it works for them, but not for me.

**Comment by ayushnoori** [comment]
Hi @Gesmira @levinhein, I have encountered the same issue. I am analyzing many single-cell studies, so have tested across several hundred Seurat objects, and always receive the same error when running `FindVariableFeatures`.

```
Error in match.arg(arg = layer, choices = Layers(object = object, search = FALSE)) : 
  'arg' should be one of “counts”, “data”, “scale.data”
```

I see that https://github.com/satijalab/seurat/issues/7092 has reported the same. May you please advise how to resolve, as I am unable to integrate datasets without identifying variable features. Thank you!

**Comment by Dragonmasterx87** [comment]
@ayushnoori can you share your pipeline, and output of `sessionInfo()`

**Comment by Gesmira** [comment]
Hi all, 
Based on your error messages, it seems that you still have the v5 version of SeuratObject loaded which is causing errors as you have only downgraded the version of Seurat, but not SeuratObject. If you clear your R environment, restart R, and run:

```
install.packages(c("SeuratObject", "Seurat"))
library(SeuratObject)
library(Seurat)
```
That should restore the older version of Seurat correctly. Let me know if that works for you.

**Comment by levinhein** [comment]
Hi @Gesmira Indeed, following your instruction reverted my Seurat version successfully to the previous version (v4.3.0). However, still the same. The error in RunPCA() still persists.

```

library(Seurat)
library(plyr)
library(dplyr)
library(cowplot)
library(ggplot2)
library(patchwork)
library(Matrix)
library(data.table)
library(tidyr)
library(ggpubr)
library(tidyverse)
library(RColorBrewer)
library(writexl)


data <- Read10X("/mnt/RAID_5/vincent/Project-PBMC/Data-PBMC-GSE157344/1/")
#B) Create Seurat object. 
PBMC15 <- CreateSeuratObject(counts = data, project = "PBMC15", min.cells = 3, min.features = 100)
#Standard pre-processing workflow
PBMC15[["percent.mt"]] <- PercentageFeatureSet(PBMC15, pattern = "^MT-") #NKD <- NKD[!grepl("^MT-", rownames(NKD)), ]
PBMC15[["percent.hb"]] <- PercentageFeatureSet(PBMC15, pattern = "^HB") # For 10% hemoglobin: https://insight.jci.org/articles/view/135678#SEC4
PBMC15[["percent.rb"]] <- PercentageFeatureSet(PBMC15, pattern = "^RP[SL][[:digit:]]|^RPLP[[:digit:]]|^RPSA")
VlnPlot(PBMC15, features=c("nFeature_RNA", "nCount_RNA", "percent.mt", "percent.rb", "CD177"), ncol = 5)
VlnPlot(PBMC15, features=c("CD8A", "CD177"))
### SUB-SETTING
PBMC15 <- subset(PBMC15, subset = nFeature_RNA > 100 & nFeature_RNA < 5000 & percent.mt < 10)
#Removal of RB, HB, MALAT1, MT genes # NOTE: According to a Nature paper, they removed rb genes. Another reference is: https://github.com/satijalab/seurat/issues/759 #filtered ribosomal genes: https://nbisweden.github.io/excelerate-scRNAseq/session-qc/scRNAseq_QC_Asa_Bjorklund_2019.pdf &&& filtering hb and malat: https://nbisweden.github.io/workshop-scRNAseq/labs/compiled/seurat/seurat_01_qc.html
PBMC15 <- PBMC15[!grepl("^MT-", rownames(PBMC15)), ] #MT genes are already removed but the column of its percent.mt values remain
PBMC15 <- PBMC15[!grepl("MALAT1", rownames(PBMC15)), ]
PBMC15 <- PBMC15[!grepl("XIST", rownames(PBMC15)), ]
PBMC15 <- PBMC15[!grepl("RSP4Y1 ", rownames(PBMC15)), ]
PBMC15 <- PBMC15[grep("^RP[SL][[:digit:]]|^RPLP[[:digit:]]|^RPSA", rownames(PBMC15), value = T, invert = T), ]
dim(PBMC15)
rm(data)

data <- Read10X("/mnt/RAID_5/vincent/Project-PBMC/Data-PBMC-GSE157344/2/")
#B) Create Seurat object. 
PBMC16 <- CreateSeuratObject(counts = data, project = "PBMC16", min.cells = 3, min.features = 100)
#Standard pre-processing workflow
PBMC16[["percent.mt"]] <- PercentageFeatureSet(PBMC16, pattern = "^MT-") #NKD <- NKD[!grepl("^MT-", rownames(NKD)), ]
PBMC16[["percent.hb"]] <- PercentageFeatureSet(PBMC16, pattern = "^HB") # For 10% hemoglobin: https://insight.jci.org/articles/view/135678#SEC4
PBMC16[["percent.rb"]] <- PercentageFeatureSet(PBMC16, pattern = "^RP[SL][[:digit:]]|^RPLP[[:digit:]]|^RPSA")
VlnPlot(PBMC16, features=c("nFeature_RNA", "nCount_RNA", "percent.mt", "percent.rb", "CD177"), ncol = 5)
VlnPlot(PBMC16, features=c("CD8A", "CD177"))
### SUB-SETTING
PBMC16 <- subset(PBMC16, subset = nFeature_RNA > 100 & nFeature_RNA < 5000 & percent.mt < 10)
#Removal of RB, HB, MALAT1, MT genes # NOTE: According to a Nature paper, they removed rb genes. Another reference is: https://github.com/satijalab/seurat/issues/759 #filtered ribosomal genes: https://nbisweden.github.io/excelerate-scRNAseq/session-qc/scRNAseq_QC_Asa_Bjorklund_2019.pdf &&& filtering hb and malat: https://nbisweden.github.io/workshop-scRNAseq/labs/compiled/seurat/seurat_01_qc.html
PBMC16 <- PBMC16[!grepl("^MT-", rownames(PBMC16)), ] #MT genes are already removed but the column of its percent.mt values remain
PBMC16 <- PBMC16[!grepl("MALAT1", rownames(PBMC16)), ]
PBMC16 <- PBMC16[!grepl("XIST", rownames(PBMC16)), ]
PBMC16 <- PBMC16[!grepl("RSP4Y1 ", rownames(PBMC16)), ]
PBMC16 <- PBMC16[grep("^RP[SL][[:digit:]]|^RPLP[[:digit:]]|^RPSA", rownames(PBMC16), value = T, invert = T), ]
dim(PBMC16)
rm(data)

data <- Read10X("/mnt/RAID_5/vincent/Project-PBMC/Data-PBMC-GSE157344/3/")
#B) Create Seurat object. 
PBMC17 <- CreateSeuratObject(counts = data, project = "PBMC17", min.cells = 3, min.features = 100)
#Standard pre-processing workflow
PBMC17[["percent.mt"]] <- PercentageFeatureSet(PBMC17, pattern = "^MT-") #NKD <- NKD[!grepl("^MT-", rownames(NKD)), ]
PBMC17[["percent.hb"]] <- PercentageFeatureSet(PBMC17, pattern = "^HB") # For 10% hemoglobin: https://insight.jci.org/articles/view/135678#SEC4
PBMC17[["percent.rb"]] <- PercentageFeatureSet(PBMC17, pattern = "^RP[SL][[:digit:]]|^RPLP[[:digit:]]|^RPSA")
VlnPlot(PBMC17, features=c("nFeature_RNA", "nCount_RNA", "percent.mt", "percent.rb", "CD177"), ncol = 5)
VlnPlot(PBMC17, features=c("CD8A", "CD177"))
### SUB-SETTING
PBMC17 <- subset(PBMC17, subset = nFeature_RNA > 100 & nFeature_RNA < 5000 & percent.mt < 10)
#Removal of RB, HB, MALAT1, MT genes # NOTE: According to a Nature paper, they removed rb genes. Another reference is: https://github.com/satijalab/seurat/issues/759 #filtered ribosomal genes: https://nbisweden.github.io/excelerate-scRNAseq/session-qc/scRNAseq_QC_Asa_Bjorklund_2019.pdf &&& filtering hb and malat: https://nbisweden.github.io/workshop-scRNAseq/labs/compiled/seurat/seurat_01_qc.html
PBMC17 <- PBMC17[!grepl("^MT-", rownames(PBMC17)), ] #MT genes are already removed but the column of its percent.mt values remain
PBMC17 <- PBMC17[!grepl("MALAT1", rownames(PBMC17)), ]
PBMC17 <- PBMC17[!grepl("XIST", rownames(PBMC17)), ]
PBMC17 <- PBMC17[!grepl("RSP4Y1 ", rownames(PBMC17)), ]
PBMC17 <- PBMC17[grep("^RP[SL][[:digit:]]|^RPLP[[:digit:]]|^RPSA", rownames(PBMC17), value = T, invert = T), ]
dim(PBMC17)
rm(data)

KD.list <- list(PBMC15, PBMC16, PBMC17)

###########  CELL CYCLE SCORING
s.genes <- cc.genes$s.genes
g2m.genes <- cc.genes$g2m.genes

# ### Normalization, Scaling, Cellcycle Scoring: https://satijalab.org/seurat/articles/cell_cycle_vignette.html
for (i in 1:length (KD.list)) {
  KD.list[[i]] <-NormalizeData(KD.list[[i]], verbose = TRUE)
  KD.list[[i]] <-FindVariableFeatures(KD.list[[i]], selection.method = "vst", nfeatures=3000, verbose = TRUE)
  KD.list[[i]] <-ScaleData(KD.list[[i]], features = rownames(KD.list[[i]]), verbose = TRUE)
  KD.list[[i]] <-RunPCA(KD.list[[i]], verbose = TRUE)
  KD.list[[i]] <-CellCycleScoring(KD.list[[i]], s.features = s.genes, g2m.features = g2m.genes, set.ident = TRUE)
}

```
![image](https://github.com/satijalab/seurat/assets/68268222/d792cc84-6c28-440d-bad5-e296d20f864a)

```
> sessionInfo()
R version 4.3.0 (2023-04-21)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 23.04

Matrix products: default
BLAS/LAPACK: /usr/lib/x86_64-linux-gnu/libmkl_rt.so;  LAPACK version 3.8.0

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

time zone: Asia/Taipei
tzcode source: system (glibc)

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
 [1] writexl_1.4.2      RColorBrewer_1.1-3 lubridate_1.9.2    forcats_1.0.0     
 [5] stringr_1.5.0      purrr_1.0.1        readr_2.1.4        tibble_3.2.1      
 [9] tidyverse_2.0.0    ggpubr_0.6.0       tidyr_1.3.0        data.table_1.14.8 
[13] patchwork_1.1.2    ggplot2_3.4.2      cowplot_1.1.1      dplyr_1.1.2       
[17] plyr_1.8.8         Seurat_4.3.0.1     SeuratObject_4.1.3 sp_1.6-1          
[21] irlba_2.3.5.1      Matrix_1.5-4.1    

loaded via a namespace (and not attached):
  [1] rstudioapi_0.14        jsonlite_1.8.5         magrittr_2.0.3        
  [4] ggbeeswarm_0.7.2       spatstat.utils_3.0-3   farver_2.1.1          
  [7] vctrs_0.6.3            ROCR_1.0-11            spatstat.explore_3.2-1
 [10] rstatix_0.7.2          htmltools_0.5.5        broom_1.0.5           
 [13] sctransform_0.3.5      parallelly_1.36.0      KernSmooth_2.23-21    
 [16] htmlwidgets_1.6.2      ica_1.0-3              plotly_4.10.2         
 [19] zoo_1.8-12             igraph_1.5.0           mime_0.12             
 [22] lifecycle_1.0.3        pkgconfig_2.0.3        R6_2.5.1              
 [25] fastmap_1.1.1          fitdistrplus_1.1-11    future_1.32.0         
 [28] shiny_1.7.4            digest_0.6.31          colorspace_2.1-0      
 [31] tensor_1.5             labeling_0.4.2         progressr_0.13.0      
 [34] fansi_1.0.4            spatstat.sparse_3.0-1  timechange_0.2.0      
 [37] httr_1.4.6             polyclip_1.10-4        abind_1.4-5           
 [40] compiler_4.3.0         withr_2.5.0            backports_1.4.1       
 [43] carData_3.0-5          viridis_0.6.3          R.utils_2.12.2        
 [46] ggsignif_0.6.4         MASS_7.3-60            tools_4.3.0           
 [49] vipor_0.4.5            lmtest_0.9-40          beeswarm_0.4.0        
 [52] httpuv_1.6.11          future.apply_1.11.0    goftest_1.2-3         
 [55] R.oo_1.25.0            glue_1.6.2             nlme_3.1-162          
 [58] promises_1.2.0.1       grid_4.3.0             Rtsne_0.16            
 [61] cluster_2.1.4          reshape2_1.4.4         generics_0.1.3        
 [64] gtable_0.3.3           spatstat.data_3.0-1    tzdb_0.4.0            
 [67] R.methodsS3_1.8.2      hms_1.1.3              car_3.1-2             
 [70] utf8_1.2.3             spatstat.geom_3.2-1    RcppAnnoy_0.0.20      
 [73] ggrepel_0.9.3          RANN_2.6.1             pillar_1.9.0          
 [76] later_1.3.1            splines_4.3.0          lattice_0.21-8        
 [79] survival_3.5-3         deldir_1.0-9           tidyselect_1.2.0      
 [82] miniUI_0.1.1.1         pbapply_1.7-0          gridExtra_2.3         
 [85] scattermore_1.2        matrixStats_1.0.0      stringi_1.7.12        
 [88] lazyeval_0.2.2         codetools_0.2-19       cli_3.6.1             
 [91] uwot_0.1.14            xtable_1.8-4           reticulate_1.30       
 [94] munsell_0.5.0          Rcpp_1.0.10            globals_0.16.2        
 [97] spatstat.random_3.1-5  png_0.1-8              ggrastr_1.0.2         
[100] parallel_4.3.0         ellipsis_0.3.2         listenv_0.9.0         
[103] viridisLite_0.4.2      scales_1.2.1           ggridges_0.5.4        
[106] leiden_0.4.3           rlang_1.1.1  
```

**Comment by ayushnoori** [comment]
> @ayushnoori can you share your pipeline, and output of `sessionInfo()` as this seems to be a current issue many are facing, yesterday I tried to generate a reprex but was unable to. Re-installing R v4.2, Rstudio, jupyter, anaconda and Seurat v4.3 results in an appropriate install after completely removing R libraries and .renviron. I am also able to run the pbmc vignette without any issues.

Hi @Dragonmasterx87, I tried @Gesmira's approach and reinstalled `SeuratObject`, which resolved the issue. It appears that the issue was with the most recent version of `SeuratObject`, since reinstalling `Seurat` alone failed to resolve the problem.

**Comment by Gesmira** [comment]
Hi @levinhein, 
I downloaded your reproducible example and I am able to successfully run the preprocessing pipeline including RunPCA(). We have the same version of irlba installed so I am unsure what may be causing your issue as I am not able to reproduce it. Was there a specific sequence of preprocessing that gave you the error?

**Comment by Gesmira** [comment]
Closing now due to lack of response. Please feel free to reopen if the error persists.

**Comment by gracajo** [comment]
Error persists.

Using v5 of seurat. Tried reinstall v5 of seurat and seurat object.

> load("seurat.RData")
> DefaultAssay(seurat) <- "RNA"
> seurat <- NormalizeData(seurat)
Performing log-normalization
0%   10   20   30   40   50   60   70   80   90   100%
[----|----|----|----|----|----|----|----|----|----|
**************************************************|
> seurat <- FindVariableFeatures(seurat, selection.method = "vst")
Calculating gene variances
0%   10   20   30   40   50   60   70   80   90   100%
[----|----|----|----|----|----|----|----|----|----|
**************************************************|
Calculating feature variances of standardized and clipped values
0%   10   20   30   40   50   60   70   80   90   100%
[----|----|----|----|----|----|----|----|----|----|
**************************************************|
Error in match.arg(arg = layer, choices = Layers(object = object, search = FALSE)) : 
  'arg' should be one of "counts", "data", "scale.data"

R version 4.2.1 (2022-06-23)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: CentOS Linux 7 (Core)

Matrix products: default
BLAS/LAPACK: /n/app/openblas/0.3.19-gcc-9.2.0/lib/libopenblas_haswellp-r0.3.19.so

Random number generation:
 RNG:     L'Ecuyer-CMRG 
 Normal:  Inversion 
 Sample:  Rejection 
 
locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C               LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8    LC_PAPER=en_US.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C             LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] grid      stats4    stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
 [1] sctransform_0.4.0.9001           ggpointdensity_0.1.0             viridis_0.6.3                   
 [4] viridisLite_0.4.2                htmltools_0.5.6.1                glue_1.6.2                      
 [7] RCurl_1.98-1.12                  cowplot_1.1.1                    scales_1.2.1                    
[10] lubridate_1.9.2                  forcats_1.0.0                    dplyr_1.1.3                     
[13] purrr_1.0.2                      readr_2.1.4                      tidyr_1.3.0                     
[16] tibble_3.2.1                     tidyverse_2.0.0                  patchwork_1.1.3                 
[19] BSgenome.Hsapiens.EnsDB.98_1.0.0 BSgenome_1.66.3                  rtracklayer_1.58.0              
[22] Biostrings_2.66.0                XVector_0.38.0                   ensembldb_2.22.0                
[25] AnnotationFilter_1.22.0          GenomicFeatures_1.50.4           AnnotationDbi_1.60.2            
[28] AnnotationHub_3.6.0              BiocFileCache_2.6.1              dbplyr_2.3.4                    
[31] rhdf5_2.42.1                     Rcpp_1.0.11                      Matrix_1.5-4.1                  
[34] data.table_1.14.8                stringr_1.5.0                    plyr_1.8.9                      
[37] magrittr_2.0.3                   ggplot2_3.4.4                    gtable_0.3.4                    
[40] gtools_3.9.4                     gridExtra_2.3                    ArchR_1.0.2                     
[43] scds_1.13.1                      scDblFinder_1.12.0               SingleCellExperiment_1.20.1     
[46] SummarizedExperiment_1.28.0      Biobase_2.58.0                   MatrixGenerics_1.10.0           
[49] matrixStats_1.0.0                SoupX_1.6.2                      Signac_1.11.9000                
[52] Seurat_4.4.0                     SeuratObject_4.9.9.9091          sp_2.1-1                        
[55] GenomicRanges_1.50.2             GenomeInfoDb_1.34.9              IRanges_2.32.0                  
[58] S4Vectors_0.36.2                 BiocGenerics_0.44.0             

loaded via a namespace (and not attached):
  [1] rappdirs_0.3.3                scattermore_1.2               bit64_4.0.5                  
  [4] knitr_1.44                    irlba_2.3.5.1                 DelayedArray_0.24.0          
  [7] KEGGREST_1.38.0               generics_0.1.3                ScaledMatrix_1.6.0           
 [10] callr_3.7.3                   RSQLite_2.3.1                 RANN_2.6.1                   
 [13] future_1.33.0                 tzdb_0.4.0                    bit_4.0.5                    
 [16] xml2_1.3.5                    spatstat.data_3.0-1           httpuv_1.6.11                
 [19] xfun_0.40                     hms_1.1.3                     promises_1.2.1               
 [22] progress_1.2.2                fansi_1.0.5                   restfulr_0.0.15              
 [25] igraph_1.5.1                  DBI_1.1.3                     htmlwidgets_1.6.2            
 [28] spatstat.geom_3.2-5           ellipsis_0.3.2                biomaRt_2.54.1               
 [31] deldir_1.0-9                  sparseMatrixStats_1.10.0      vctrs_0.6.4                  
 [34] remotes_2.4.2.1               Cairo_1.6-1                   ROCR_1.0-11                  
 [37] abind_1.4-5                   cachem_1.0.8                  withr_2.5.1                  
 [40] progressr_0.14.0              GenomicAlignments_1.34.1      prettyunits_1.2.0            
 [43] scran_1.26.2                  goftest_1.2-3                 cluster_2.1.3                
 [46] dotCall64_1.0-2               lazyeval_0.2.2                crayon_1.5.2                 
 [49] spatstat.explore_3.2-3        edgeR_3.40.2                  pkgconfig_2.0.3              
 [52] ProtGenerics_1.30.0           nlme_3.1-157                  vipor_0.4.5                  
 [55] rlang_1.1.1                   globals_0.16.2                lifecycle_1.0.3              
 [58] miniUI_0.1.1.1                filelock_1.0.2                rsvd_1.0.5                   
 [61] rprojroot_2.0.3               polyclip_1.10-6               lmtest_0.9-40                
 [64] Rhdf5lib_1.20.0               zoo_1.8-12                    beeswarm_0.4.0               
 [67] ggridges_0.5.4                processx_3.8.1                png_0.1-8                    
 [70] rjson_0.2.21                  bitops_1.0-7                  KernSmooth_2.23-20           
 [73] spam_2.9-1                    rhdf5filters_1.10.1           pROC_1.18.2                  
 [76] blob_1.2.4                    DelayedMatrixStats_1.20.0     parallelly_1.36.0            
 [79] spatstat.random_3.1-6         beachmat_2.14.2               memoise_2.0.1                
 [82] ica_1.0-3                     zlibbioc_1.44.0               compiler_4.2.1               
 [85] dqrng_0.3.1                   BiocIO_1.8.0                  RColorBrewer_1.1-3           
 [88] fitdistrplus_1.1-11           Rsamtools_2.14.0              cli_3.6.1                    
 [91] listenv_0.9.0                 pbapply_1.7-2                 ps_1.7.5                     
 [94] MASS_7.3-57                   tidyselect_1.2.0              stringi_1.7.12               
 [97] yaml_2.3.7                    BiocSingular_1.14.0           locfit_1.5-9.7               
[100] ggrepel_0.9.4                 timechange_0.2.0              fastmatch_1.1-4              
[103] tools_4.2.1                   future.apply_1.11.0           parallel_4.2.1               
[106] rstudioapi_0.14               bluster_1.8.0                 metapod_1.6.0                
[109] Rtsne_0.16                    digest_0.6.33                 BiocManager_1.30.22          
[112] shiny_1.7.5.1                 scuttle_1.8.4                 BiocVersion_3.16.0           
[115] later_1.3.1                   RcppAnnoy_0.0.21              httr_1.4.7                   
[118] colorspace_2.1-0              XML_3.99-0.14                 tensor_1.5                   
[121] reticulate_1.34.0             splines_4.2.1                 uwot_0.1.16                  
[124] RcppRoll_0.3.0                statmod_1.5.0                 spatstat.utils_3.0-3         
[127] scater_1.26.1                 xgboost_1.7.5.1               plotly_4.10.2                
[130] xtable_1.8-4                  jsonlite_1.8.7                R6_2.5.1                     
[133] pillar_1.9.0                  mime_0.12                     fastmap_1.1.1                
[136] BiocParallel_1.32.6           BiocNeighbors_1.16.0          interactiveDisplayBase_1.36.0
[139] codetools_0.2-18              pkgbuild_1.4.0                utf8_1.2.3                   
[142] lattice_0.20-45               spatstat.sparse_3.0-2         curl_5.1.0                   
[145] ggbeeswarm_0.7.2              leiden_0.4.3                  survival_3.3-1               
[148] limma_3.54.2                  aggregation_1.0.1             desc_1.4.2                   
[151] munsell_0.5.0                 GenomeInfoDbData_1.2.9        reshape2_1.4.4
