### ISSUE TITLE
CreateSeuratObject

### ISSUE THREAD

**Issue by Dalhte** [satijalab/seurat#8089]
Hello there
I have a problem with CreateSeuratObject (it was functioning just fine up until some massive librairies update)

Here is the code :
###Download RNA data
# Load data PG2
filt.matrixPG2 <- Read10X_h5("/media/david/F/RN7.2/PG2RN7/outs/filtered_feature_bc_matrix.h5",use.names = T)
raw.matrixPG2  <- Read10X_h5("/media/david/F/RN7.2/PG2RN7/outs/raw_feature_bc_matrix.h5",use.names = T)
cts.raw.matrixPG2 <- raw.matrixPG2$`Gene Expression`
cts.filt.matrixPG2 <- filt.matrixPG2$`Gene Expression`

#Soupx
#quick clustering

sratPG2  <- CreateSeuratObject(counts = cts.filt.matrixPG2)

And the error :
> sratPG2  <- CreateSeuratObject(counts = cts.filt.matrixPG2)
Avis : Feature names cannot have underscores ('_'), replacing with dashes ('-')
Erreur dans .Call("CRsparse_colSums", x, na.rm, FALSE, sparseResult) : 
  "CRsparse_colSums" not resolved from current namespace (Matrix)

I tried to reupload the Matrix package but it's not doing anything.
Can you help ?
Best David

**Comment by Dalhte** [comment]
I found the problem but still don't know the reason :+1: As I do multiomic analysis I also use the 
> library(TFBSTools)
And that is the only line when activated creating the problem. When I deactivate it, everything is running just fine!

**Comment by Gesmira** [comment]
Hi, 
It seems that this issue is a result of incompatible updates of CRAN and Bioconductor packages. Although we haven't precisely diagnosed it, we have been able to fix this issue with the following steps: 

- Ensure you have R version 4.3 or update to it.  
- In a fresh R session, update Bioconductor with the following call:
```
BiocManager::install(version = "3.18")
```

- When prompted if you would like to update all packages, say yes. This will then update a series of Bioconductor packages which may take up to an hour. 

At this point, the issue should be fixed. Let us know if you continue to encounter problems.

**Comment by Kamilloo1234** [comment]
> Hi, It seems that this issue is a result of incompatible updates of CRAN and Bioconductor packages. Although we haven't precisely diagnosed it, we have been able to fix this issue with the following steps:
> 
>     * Ensure you have R version 4.3 or update to it.
> 
>     * In a fresh R session, update Bioconductor with the following call:
> 
> 
> ```
> BiocManager::install(version = "3.18")
> ```
> 
>     * When prompted if you would like to update all packages, say yes. This will then update a series of Bioconductor packages which may take up to an hour.
> 
> 
> At this point, the issue should be fixed. Let us know if you continue to encounter problems.


Hi, I also have the same problem even if I do:
BiocManager::install(version = "3.18")  and I updated all needed packages, too.

When I run
FindMarkers(sample.combined, ident.1 = 'Microglia_A', ident.2 = 'Microglia_B')
I am getting the error

Error in .local(x, na.rm, dims, ...) : 
  Object 'CRsparse_rowSums' not found

A month ago, everything worked perfect, when I loaded my saved workspace and did "FindMarkers"  :-(

What else can we do?

**Comment by sgolomb** [comment]
Hello, I am also still having this problem after trying BiocManager::install(version = "3.18"), updating packages and uninstalling the Azimuth package.

I am experiencing this problem on both non-integrated and integrated reductions in my Seurat object.

Same error as reported above:
Error in .local(x, na.rm, dims, ...) : 
  object 'CRsparse_colSums' not found

**Comment by dcollins15** [comment]
An updated solution is available [here](https://github.com/satijalab/seurat/issues/8202).

Upgrading `Bioconductor` to v3.18 _may_ have resolved this issue if in the process `TFBSTools` was rebuilt using the latest `Matrix`. The linked solution should hopefully work for folks who are still struggling.

**Comment by Plasmiddddd** [comment]
Hey! Sorry I tried all above include [update Bioconductor](https://github.com/satijalab/seurat/issues/8089#issuecomment-1847816493), [ reinstall TFBSTools](https://github.com/satijalab/seurat/issues/8202), and [update all packages](https://github.com/satijalab/seurat/issues/8094#issuecomment-1829790858); Unfortunately, None of them work. The only way I found is not to load the Azimuth package.
